### ISSUE TITLE
1.7.10 Loot Bags crash in crafting 3x3

### ISSUE THREAD

**Issue by Cazadorsniper** [Malorolam/LootBags#10]
Each time I try to craft common loot bags into 1 uncommon loot bag in a 3x3 crafting grid the client crashes, I tested this crash on 4 different 3x3 crafting grids (Vanilla, Natura, Tinkers' Construct, and Applied Energistics 2). The internal 2x2 crafting grid works fine however. 
Here is my config file: http://pastebin.com/awcZ7xw2
Vanilla crash: http://pastebin.com/MqK16TxG
TConstruct crash: http://pastebin.com/SHwE9SXU
AE2 crash: http://pastebin.com/B421aFHi
Natura crash: http://pastebin.com/Riy4Rnbu

**Comment by Malorolam** [comment]
Fixed in 2.0.1.
