### ISSUE TITLE
Lootbags shows everywhere in creative

### ISSUE THREAD

**Issue by NishiPlays** [Malorolam/LootBags#100]
![screenshot 10](https://user-images.githubusercontent.com/34257194/33585762-e6f91334-d933-11e7-85ae-d804de197843.png)
![screenshot 11](https://user-images.githubusercontent.com/34257194/33585766-ecf6a5bc-d933-11e7-87f0-475e2d60f7e1.png)

**Comment by NishiPlays** [comment]
Sorry forgot to give some info. In 1.12.2-2.5.1 version, using forge 1.12.2 - 14.23.1.2559

**Comment by Malorolam** [comment]
Fixed in 2.5.2
