### ISSUE TITLE
1.12.2 Whitelist

### ISSUE THREAD

**Issue by Kasparsunekaer** [Malorolam/LootBags#102]
Hey

im having some problems with Whitelist 

This is my config for example: lootbag_Legendary:4 and see photo of what JEI tells me the bag can drop and when opening some lootbags i also get items that isnt on the whitelist

$STARTBAG:lootbag_Legendary:4

    $ISSECRET:false
    $BAGTEXTCOLOR:$GOLD
    $BAGTEXTUNOPENED:$AQUA:Ooh, what could be inside?
    $BAGTEXTOPENED:What's inside is not as interesting as not knowing.
    $BAGTEXTSHIFT:$DROPCHANCES
    $BAGVALUE:256:256
    $PASSIVESPAWNWEIGHT:5
    $PLAYERSPAWNWEIGHT:5
    $MOBSPAWNWEIGHT:10
    $BOSSSPAWNWEIGHT:15
    $USEGENERALLOOTSOURCES:true
    $MAXIMUMITEMS:5
    $MINIMUMITEMS:1
    $MAXIMUMGENERALLOOTWEIGHT:5
    $MINIMUMGENERALLOOTWEIGHT:-1
    $PREVENTITEMREPEATS:none
    $EXCLUDEENTITIES:false
	$STARTWHITELIST
        minecraft:diamond_helmet:0:1:1:15
        minecraft:diamond_chestplate:0:1:1:15
        minecraft:diamond_leggings:0:1:1:15
        minecraft:diamond_boots:0:1:1:15
        minecraft:end_portal_frame:0:1:1:10
        minecraft:diamond_horse_armor:0:1:1:10
        minecraft:skull:1:1:3:20
        minecraft:golden_apple:1:1:1:10
    $ENDWHITELIST
    $STARTBLACKLIST
        lootbags:itemlootbag:0
    $ENDBLACKLIST
$ENDBAG:lootbag_Legendary

![lootbag_legendary](https://user-images.githubusercontent.com/18720460/33686240-85bed368-dad4-11e7-8c5b-72c9baacca99.PNG)

Lootbag: LootBags-1.12.2-2.5.2
Forge: forge-14.23.1.2559

**Comment by Malorolam** [comment]
$USEGENERALLOOTSOURCES:true
is your problem.  That means that the bag will pull from the general loot table as well as whitelist items.

**Comment by Kasparsunekaer** [comment]
Thanks!
