### ISSUE TITLE
Bag Storage doesn't work

### ISSUE THREAD

**Issue by Kevin--Zhang** [Malorolam/LootBags#103]
Bag storage doesn't seem to take from any source or input.

**Comment by Malorolam** [comment]
I need the lootbags.cfg and Lootbags_BagConfig.cfg files.

**Comment by Kevin--Zhang** [comment]
Where are those located? They are in the JAR?

**Comment by Malorolam** [comment]
No, in the instance folder (one folder up from where the mods are), there's a folder called config, they're in there.

**Comment by Kevin--Zhang** [comment]
# Configuration file

"blacklisted items" {
    # Adding a modid and internal item name to this list will remove the item from the general loot table.  The entry must be in the form <modid>:<itemname>:<damage> on a single line or it won't work right.  Example to blacklist iron ingots: minecraft:iron_ingot:0.  An entire modcan be blacklisted by just entering the modid and nothing else.
    S:"Global Blacklist" <
        
     >
}


"drop chances" {
    # This is the resolution of the bag drop chances.  Only change this if you want bags with rarity resolutions > 0.1%
    I:"1 Weighting Resolution"=1000
}


general {
    # The bag ID (see the bag config) used in the recycler to fabricate new bags.
    I:"Bag ID used in Recycler"=0

    # The cooldown in ticks that the bag opener needs before it'll process again.
    I:"Bag Opener Cooldown"=100

    # Setting this to true will display extra information about the contents of the bags and tables.
    B:"Debug Mode"=false

    # Disables the bag opener from being crafted.
    B:"Disable Opener Recipe"=false

    # Disables the loot recycler from being crafted.
    B:"Disable Recycler Recipe"=false

    # Disables the bag storage from being crafted.
    B:"Disable Storage Recipe"=false

    # This limits the loot bags to only drop one bag.  Bag weighting is dependant on drop chances.
    B:"Limit bag drop to one bag per death"=true

    # If the bag encounters an item it cannot place in the bag for some reason, it will reroll until it gets an item that will work, this sets a limit to the number of times the bag will reroll before it just skips the slot.  Extremely high or low numbers may result in undesired performance of the mod.
    I:"Maximum Rerolls Allowed"=50

    # If set to true, prevents bag storage from accepting opened bags.
    B:"Prevent Merging Opened Bags"=false

    # This if true will show all the secret bags in creative inventory or item list mods.  Kind of ruins the fun if you ask me.
    B:"Show Secret Bags"=false

    # This is kind of ambiguous, but essentially it's the value of loot stuff needed to fabricate new bags in the loot recycler.
    I:"Total Loot Value to Create a New Bag"=1000

    # Sources of entity death that are counted to determine if a bag can drop.  Allowable names: All, Player, Real.  All is any source of death, Player is any player entity including mod fake players, Real is only real players.
    S:"Valid Kill Methods"=All

    # Setting this to false will disable many of the info messages, only showing errors in the log.
    B:"Verbose Mode"=false
}


"loot categories" {
    # This is a list of the loot sources the bags pull from to generate the loot tables.  Probably a good idea to not mess with this unless you know what you're doing as entering in a category that doesn't exist will simply make a new.
    S:"ChestGenHooks Dropped" <
        minecraft:chests/simple_dungeon
        minecraft:chests/abandoned_mineshaft
        minecraft:chests/desert_pyramid
        minecraft:chests/jungle_temple
        minecraft:chests/jungle_temple_dispenser
        minecraft:chests/stronghold_corridor
        minecraft:chests/stronghold_crossing
        minecraft:chests/stronghold_library
        minecraft:chests/village_blacksmith
        minecraft:chests/end_city_treasure
        minecraft:chests/nether_bridge
        minecraft:chests/igloo_chest
     >
}


recycler {
    # Blacklist an item from being recyclable.  The entry must be in the form <modid>:<itemname>:<damage> on a single line or it won't work right.
    S:"Item Blacklist" <
     >

    # Whitelist an item to be recyclable.  The entry must be in the form <modid>:<itemname>:<damage>:<weighting>:[<nbt data (seriously don't try to make this by hand)> (optional)]  The weight is as though the item was added to a bag, but the items whitelisted are not added to any loot bags.
    S:"Item Whitelist" <
     >

    # Divides the recycler value of an item in the Recycler by this if the item does not stack past one item, in the formula (a*Total Value)/(Item Value*(isStackable)?(b):(c)), this is the c variable.
    D:"Non-Stackable Formula Divider"=1.0

    # Divides the recycler value of an item in the Recycler by this if the item stacks past one item, in the formula (a*Total Value)/(Item Value*(isStackable)?(b):(c)), this is the b variable.
    D:"Stackable Formula Divider"=8.0

    # Multiplies the recycler value of an item in the Recycler, in the formula (a*Total Value)/(Item Value*(isStackable)?(b):(c)), this is the a variable.
    D:"Value Formula Multiplier"=1.5
}


"whitelisted items" {
    # Adding a modid and internal item name to this list will add the item to the Loot Bag drop table.  The entry must be in the form <modid>:<itemname>:<damage>:<min stack size>:<max stack size>:<weighting>:[<nbt data (seriously don't try to make this by hand)> (optional)]  Example to whitelist up to 16 iron ingots with a weight of 50: minecraft:iron_ingot:0:1:16:50.
    S:"Global Whitelist" <
     >
}

**Comment by Kevin--Zhang** [comment]
$STARTBAG:lootbag_Common:0
    $ISSECRET:false
    $BAGTEXTCOLOR:$WHITE
    $BAGTEXTUNOPENED:$AQUA:Ooh, what could be inside?
    $BAGTEXTOPENED:What's inside is not as interesting as not knowing.
    $BAGTEXTSHIFT:$DROPCHANCES
    $BAGVALUE:1:1
    $PASSIVESPAWNWEIGHT:50
    $PLAYERSPAWNWEIGHT:100
    $MOBSPAWNWEIGHT:100
    $BOSSSPAWNWEIGHT:200
    $USEGENERALLOOTSOURCES:true
    $MAXIMUMITEMS:5
    $MINIMUMITEMS:1
    $MAXIMUMGENERALLOOTWEIGHT:-1
    $MINIMUMGENERALLOOTWEIGHT:-1
    $PREVENTITEMREPEATS:none
    $EXCLUDEENTITIES:false
    $STARTBLACKLIST
        lootbags:itemlootbag:0
    $ENDBLACKLIST
$ENDBAG:lootbag_Common
$STARTBAG:lootbag_Uncommon:1
    $ISSECRET:false
    $BAGTEXTCOLOR:$GREEN
    $BAGTEXTUNOPENED:$AQUA:Ooh, what could be inside?
    $BAGTEXTOPENED:What's inside is not as interesting as not knowing.
    $BAGTEXTSHIFT:$DROPCHANCES
    $BAGVALUE:4:4
    $PASSIVESPAWNWEIGHT:25
    $PLAYERSPAWNWEIGHT:50
    $MOBSPAWNWEIGHT:50
    $BOSSSPAWNWEIGHT:100
    $USEGENERALLOOTSOURCES:true
    $MAXIMUMITEMS:5
    $MINIMUMITEMS:1
    $MAXIMUMGENERALLOOTWEIGHT:20
    $MINIMUMGENERALLOOTWEIGHT:-1
    $PREVENTITEMREPEATS:none
    $EXCLUDEENTITIES:false
    $STARTBLACKLIST
        lootbags:itemlootbag:0
    $ENDBLACKLIST
$ENDBAG:lootbag_Uncommon
$STARTBAG:lootbag_Rare:2
    $ISSECRET:false
    $BAGTEXTCOLOR:$BLUE
    $BAGTEXTUNOPENED:$AQUA:Ooh, what could be inside?
    $BAGTEXTOPENED:What's inside is not as interesting as not knowing.
    $BAGTEXTSHIFT:$DROPCHANCES
    $BAGVALUE:16:16
    $PASSIVESPAWNWEIGHT:15
    $PLAYERSPAWNWEIGHT:15
    $MOBSPAWNWEIGHT:25
    $BOSSSPAWNWEIGHT:50
    $USEGENERALLOOTSOURCES:true
    $MAXIMUMITEMS:5
    $MINIMUMITEMS:1
    $MAXIMUMGENERALLOOTWEIGHT:15
    $MINIMUMGENERALLOOTWEIGHT:-1
    $PREVENTITEMREPEATS:none
    $EXCLUDEENTITIES:false
    $STARTBLACKLIST
        lootbags:itemlootbag:0
    $ENDBLACKLIST
$ENDBAG:lootbag_Rare
$STARTBAG:lootbag_Epic:3
    $ISSECRET:false
    $BAGTEXTCOLOR:$LIGHT_PURPLE
    $BAGTEXTUNOPENED:$AQUA:Ooh, what could be inside?
    $BAGTEXTOPENED:What's inside is not as interesting as not knowing.
    $BAGTEXTSHIFT:$DROPCHANCES
    $BAGVALUE:64:64
    $PASSIVESPAWNWEIGHT:10
    $PLAYERSPAWNWEIGHT:10
    $BOSSSPAWNWEIGHT:15
    $MOBSPAWNWEIGHT:25
    $USEGENERALLOOTSOURCES:true
    $MAXIMUMITEMS:5
    $MINIMUMITEMS:1
    $MAXIMUMGENERALLOOTWEIGHT:10
    $MINIMUMGENERALLOOTWEIGHT:-1
    $PREVENTITEMREPEATS:none
    $EXCLUDEENTITIES:false
    $STARTBLACKLIST
        lootbags:itemlootbag:0
    $ENDBLACKLIST
$ENDBAG:lootbag_Epic
$STARTBAG:lootbag_Legendary:4
    $ISSECRET:false
    $BAGTEXTCOLOR:$GOLD
    $BAGTEXTUNOPENED:$AQUA:Ooh, what could be inside?
    $BAGTEXTOPENED:What's inside is not as interesting as not knowing.
    $BAGTEXTSHIFT:$DROPCHANCES
    $BAGVALUE:256:256
    $PASSIVESPAWNWEIGHT:5
    $PLAYERSPAWNWEIGHT:5
    $MOBSPAWNWEIGHT:10
    $BOSSSPAWNWEIGHT:15
    $USEGENERALLOOTSOURCES:true
    $MAXIMUMITEMS:5
    $MINIMUMITEMS:1
    $MAXIMUMGENERALLOOTWEIGHT:5
    $MINIMUMGENERALLOOTWEIGHT:-1
    $PREVENTITEMREPEATS:none
    $EXCLUDEENTITIES:false
    $STARTBLACKLIST
        lootbags:itemlootbag:0
    $ENDBLACKLIST
$ENDBAG:lootbag_Legendary
$STARTBAG:lootbag_Artifact:11
    $BAGCOLOR:244|167|66:89|79|53
    $ISSECRET:false
    $BAGTEXTCOLOR:$YELLOW
    $BAGTEXTUNOPENED:$AQUA:One of a kind?
    $BAGTEXTOPENED:No, not really.
    $BAGTEXTSHIFT:$WHITE:Hopefully not a supernova on a stick.
    $BAGVALUE:1024:1024
    $PASSIVESPAWNWEIGHT:1
    $PLAYERSPAWNWEIGHT:1
    $MOBSPAWNWEIGHT:1
    $BOSSSPAWNWEIGHT:1
    $USEGENERALLOOTSOURCES:true
    $MAXIMUMITEMS:3
    $MINIMUMITEMS:1
    $MAXIMUMGENERALLOOTWEIGHT:2
    $MINIMUMGENERALLOOTWEIGHT:-1
    $PREVENTITEMREPEATS:none
    $EXCLUDEENTITIES:false
    $STARTWHITELIST
        lootbags:itemlootbag:12:1:1:1
    $ENDWHITELIST
$ENDBAG:lootbag_Artifact
$STARTBAG:lootbag_Old_Blue:12
    $BAGCOLOR:84|89|142:17|23|84
    $ISSECRET:true
    $BAGTEXTCOLOR:$BLUE
    $BAGTEXTUNOPENED:$BLUE:A mysterious blue bag that
    $BAGTEXTUNOPENED:$BLUE:seems to hold something inside.
    $BAGTEXTOPENED:$BLUE:I don't know what I expected.
    $BAGTEXTSHIFT:$BLUE:You'll have to open it to find out.
    $BAGVALUE:0:64
    $PASSIVESPAWNWEIGHT:0
    $PLAYERSPAWNWEIGHT:0
    $MOBSPAWNWEIGHT:0
    $BOSSSPAWNWEIGHT:0
    $USEGENERALLOOTSOURCES:true
    $MAXIMUMITEMS:1
    $MINIMUMITEMS:1
    $MAXIMUMGENERALLOOTWEIGHT:-1
    $MINIMUMGENERALLOOTWEIGHT:15
    $PREVENTITEMREPEATS:none
    $EXCLUDEENTITIES:false
    $STARTWHITELIST
        lootbags:itemlootbag:12:1:1:20
    $ENDWHITELIST
$ENDBAG:lootbag_Old_Blue
$STARTBAG:lootbag_Bacon:5
    $ISSECRET:true
    $BAGTEXTCOLOR:§d
    $BAGTEXTUNOPENED:$AQUA:Ooh, what could be inside?
    $BAGTEXTOPENED:§d:Turns out there is bacon inside...
    $BAGTEXTSHIFT:§7:Three out of every four bacons agree that they don't have enough bacon. The fourth has a bag full of bacon.
    $BAGTEXTSHIFT:§b:(It still isn't enough bacon.)
    $BAGVALUE:-1:-1
    $PASSIVESPAWNWEIGHT:25
    $PLAYERSPAWNWEIGHT:25
    $MOBSPAWNWEIGHT:25
    $BOSSSPAWNWEIGHT:25
    $USEGENERALLOOTSOURCES:false
    $MAXIMUMITEMS:3
    $MINIMUMITEMS:1
    $PREVENTITEMREPEATS:none
    $EXCLUDEENTITIES:true
    $STARTENTITYLIST
        $VISIBLENAME:bacon_donut
    $ENDENTITYLIST
    $STARTWHITELIST
        minecraft:porkchop:0:1:8:20
        minecraft:cooked_porkchop:0:1:8:20
    $ENDWHITELIST
$ENDBAG:lootbag_Bacon
$STARTBAG:lootbag_Worn_Out:6
    $BAGCOLOR:97|28|161:16|145|14
    $ISSECRET:true
    $BAGTEXTCOLOR:$GRAY
    $BAGTEXTUNOPENED:$AQUA:Ooh, what could be inside?
    $BAGTEXTOPENED:The Fluffiest of Truth.
    $BAGTEXTSHIFT:My bags are not configured to drop beds in this pack. I am 100% certain about this.
    $BAGTEXTSHIFT:$DARK_PURPLE:~Malorolam
    $BAGVALUE:-1:-1
    $PASSIVESPAWNWEIGHT:25
    $PLAYERSPAWNWEIGHT:25
    $MOBSPAWNWEIGHT:25
    $BOSSSPAWNWEIGHT:25
    $USEGENERALLOOTSOURCES:false
    $MAXIMUMITEMS:1
    $MINIMUMITEMS:1
    $PREVENTITEMREPEATS:item
    $EXCLUDEENTITIES:true
    $STARTENTITYLIST
        $VISIBLENAME:Malorolam
    $ENDENTITYLIST
    $STARTWHITELIST
        minecraft:bed:0:1:1:20:31|-117|8|0|0|0|0|0|0|0|-29|98|96|96|102|-32|10|74|45|72|-52|44|114|-50|47|46|97|0|2|46|6|-10|-108|-52|-30|-126|-100|-60|74|14|6|22|-65|-60|-36|84|6|78|-65|-4|18|5|71|5|-89|-44|20|6|6|0|122|-45|0|-36|50|0|0|0
    $ENDWHITELIST
$ENDBAG:lootbag_Worn_Out
$STARTBAG:lootbag_Soaryn:7
    $ISSECRET:true
    $BAGTEXTCOLOR:$BLUE
    $BAGTEXTUNOPENED:$AQUA:Ooh, what could be inside?
    $BAGTEXTOPENED:Everytime a random chest is placed, a Soaryn gets more Chick Fil A.
    $BAGTEXTSHIFT:One out of every four chests is a Soaryn chest. Only you can prevent inventory clutter by creating more.
    $BAGVALUE:-1:-1
    $PASSIVESPAWNWEIGHT:25
    $PLAYERSPAWNWEIGHT:25
    $MOBSPAWNWEIGHT:25
    $BOSSSPAWNWEIGHT:25
    $USEGENERALLOOTSOURCES:false
    $MAXIMUMITEMS:3
    $MINIMUMITEMS:3
    $PREVENTITEMREPEATS:item
    $EXCLUDEENTITIES:true
    $STARTENTITYLIST
        $VISIBLENAME:Soaryn
    $ENDENTITYLIST
    $STARTWHITELIST
        minecraft:chest:0:1:2:20
        minecraft:stick:0:1:1:20
        minecraft:quartz:0:4:4:20
    $ENDWHITELIST
$ENDBAG:lootbag_Soaryn
$STARTBAG:lootbag_Wyld:8
    $ISSECRET:true
    $BAGTEXTCOLOR:$RED
    $BAGTEXTUNOPENED:$AQUA:Ooh, what could be inside?
    $BAGTEXTOPENED:Raise your Cluckingtons!
    $BAGTEXTSHIFT:Cluck Cluck...
    $BAGVALUE:-1:-1
    $PASSIVESPAWNWEIGHT:25
    $PLAYERSPAWNWEIGHT:25
    $MOBSPAWNWEIGHT:25
    $BOSSSPAWNWEIGHT:25
    $USEGENERALLOOTSOURCES:false
    $MAXIMUMITEMS:1
    $MINIMUMITEMS:1
    $PREVENTITEMREPEATS:item
    $EXCLUDEENTITIES:true
    $STARTENTITYLIST
        $VISIBLENAME:Wyld
    $ENDENTITYLIST
    $STARTWHITELIST
        minecraft:spawn_egg:0:1:1:20:31|-117|8|0|0|0|0|0|0|0|-29|98|96|-32|98|-32|116|-51|43|-55|44|-87|12|73|76|-25|96|96|-54|76|97|96|119|-50|-56|76|-50|78|-51|99|96|0|0|104|-97|-118|-19|31|0|0|0
    $ENDWHITELIST
$ENDBAG:lootbag_Wyld
$STARTBAG:lootbag_Bat:9
    $ISSECRET:true
    $BAGTEXTCOLOR:$DARK_GRAY
    $BAGTEXTUNOPENED:$DARK_GREEN:A hero with no praise or glory.
    $BAGTEXTOPENED:$GREEN:Paging Doctor Bat, paging Doctor Bat! Is there a Doctor Bat in the room?
    $BAGTEXTSHIFT:$DARK_GRAY:Stop touching me! I am the night! I am the night!
    $BAGVALUE:-1:-1
    $PASSIVESPAWNWEIGHT:25
    $PLAYERSPAWNWEIGHT:25
    $MOBSPAWNWEIGHT:25
    $BOSSSPAWNWEIGHT:25
    $USEGENERALLOOTSOURCES:false
    $MAXIMUMITEMS:1
    $MINIMUMITEMS:1
    $PREVENTITEMREPEATS:item
    $EXCLUDEENTITIES:true
    $STARTENTITYLIST
        $VISIBLENAME:Batman
        $INTERNALNAME:Bat
    $ENDENTITYLIST
    $STARTWHITELIST
        minecraft:spawn_egg:0:1:1:20:31|-117|8|0|0|0|0|0|0|0|-29|98|96|-32|98|-32|116|-51|43|-55|44|-87|12|73|76|-25|96|96|-54|76|97|96|118|74|44|97|96|0|0|110|124|-90|-64|27|0|0|0
    $ENDWHITELIST
$ENDBAG:lootbag_Bat
$STARTBAG:lootbag_Darkosto:10
    $ISSECRET:true
    $BAGTEXTCOLOR:$GRAY
    $BAGTEXTUNOPENED:$DARK_RED:The most fitting of loot.
    $BAGTEXTOPENED:$YELLOW:Happy Birthday Darkosto ~ Wyld
    $BAGTEXTSHIFT:$DARK_RED:Only drops on a certain special day.
    $BAGVALUE:-1:-1
    $PASSIVESPAWNWEIGHT:25
    $PLAYERSPAWNWEIGHT:25
    $MOBSPAWNWEIGHT:25
    $BOSSSPAWNWEIGHT:25
    $USEGENERALLOOTSOURCES:false
    $MAXIMUMITEMS:5
    $MINIMUMITEMS:3
    $PREVENTITEMREPEATS:none
    $EXCLUDEENTITIES:true
    $STARTENTITYLIST
        $VISIBLENAME:Darkosto
    $ENDENTITYLIST
    $STARTWHITELIST
        minecraft:cake:0:1:1:20
    $ENDWHITELIST
$ENDBAG:lootbag_Darkosto
$STARTBAG:lootbag_Patient:13
    $ISSECRET:true
    $BAGCOLOR:71|0|0:0|0|0
    $BAGTEXTCOLOR:$GRAY
    $BAGTEXTUNOPENED:$DARK_RED:Eventually it may be valuable.
    $BAGTEXTOPENED:$DARK_RED:Were you patient enough?
    $BAGTEXTSHIFT:$DARK_RED:Waiting is the best game of all.
    $BAGVALUE:-1:-1
    $PASSIVESPAWNWEIGHT:5
    $PLAYERSPAWNWEIGHT:5
    $MOBSPAWNWEIGHT:5
    $BOSSSPAWNWEIGHT:5
    $USEGENERALLOOTSOURCES:false
    $MAXIMUMITEMS:1
    $MINIMUMITEMS:1
    $PREVENTITEMREPEATS:none
    $EXCLUDEENTITIES:true
    $BLACKLISTRECYCLER:true
    $STARTENTITYLIST
        $INTERNALNAME:Zombie
    $ENDENTITYLIST
    $STARTWHITELIST
        minecraft:nether_star:0:1:1:1
        lootbags:itemlootbag:13:1:1:9999
    $ENDWHITELIST
$ENDBAG:lootbag_Patient
$STARTBAG:lootbag_Direwolf:20
    $BAGCOLOR:93|181|204:70|71|135
    $ISSECRET:true
    $BAGTEXTCOLOR:$AQUA
    $BAGTEXTUNOPENED:$AQUA:Hello Everyone!
    $BAGTEXTOPENED:$AQUA:Take it easy!
    $BAGTEXTSHIFT:Enclosed is everything one needs to
    $BAGTEXTSHIFT:make their very own Direwolf20 9x9!
    $BAGTEXTSHIFT:$AQUA:(Door and lighting sold separately)
    $BAGVALUE:-1:-1
    $PASSIVESPAWNWEIGHT:25
    $PLAYERSPAWNWEIGHT:25
    $MOBSPAWNWEIGHT:25
    $BOSSSPAWNWEIGHT:25
    $USEGENERALLOOTSOURCES:false
    $MAXIMUMITEMS:5
    $MINIMUMITEMS:5
    $PREVENTITEMREPEATS:fixed
    $EXCLUDEENTITIES:true
    $BLACKLISTRECYCLER:true
    $STARTENTITYLIST
        $VISIBLENAME:Direwolf20
    $ENDENTITYLIST
    $STARTWHITELIST
        minecraft:stone:0:64:64:20
        minecraft:stone:0:64:64:20
        minecraft:stone:0:64:64:20
        minecraft:stone:0:62:62:20
        minecraft:glass:0:36:36:20
    $ENDWHITELIST
$ENDBAG:lootbag_Direwolf

**Comment by Malorolam** [comment]
Configs look okay.  Step-by-step, what are you trying to do, as precisely as possible.

**Comment by Kevin--Zhang** [comment]
I'm trying to put bags into the bag storage block either manually or using a hopper to connect from the loot recycler to the bag storage but it doesn't seem to go through.

**Comment by Malorolam** [comment]
It'll be fixed in 2.5.3.
