### ISSUE TITLE
lootbags won't open

### ISSUE THREAD

**Issue by asiazaiser** [Malorolam/LootBags#105]
sometimes i'll get lootbags from mobs and when attempting to open them they won't? i'll right click and nothing happens , same with left click

**Comment by Malorolam** [comment]
I need the two config files.

**Comment by ReverseStateMonad** [comment]
Are you looking at a block when it happens?  I've noticed that if you have a block highlighted it will assume you're trying to right-click the block and not do anything (or interact with the block if it's a chest or the like), but if you change your view so you're looking at empty space it will open the bag.

**Comment by IamAlathe** [comment]
@ReverseStateMonad 's statement is exactly correct.  Even if the block you are looking at is not an interactable block.  Wood slabs and stone stair which make up my house cause this issue.  You have to not be looking at anything for it to work.  This is good if you have a bag in your hand and want to open a door or chest, but it does mean you have to pay attention when trying to open a bag.  I'll see if I can remember to find the config files when I get home, maybe that will help pin the issue down. :)
