### ISSUE TITLE
Loot Bag Storage Eats Bags when Piped In

### ISSUE THREAD

**Issue by scotty9090** [Malorolam/LootBags#106]
Minecraft: 1.12.2
Forge: 14.23.1.2566
Loot Bags: 1.12.2-2.5.3b

I'm trying to pipe bags into the Loot Bag Storage block.  They seem to pipe in okay (I can visualize them going through the item duct), but the stored bags counter does not move.  Manually inserting bags works fine of course.  I've tried with TE Item Ducts and EU2 transfer pipes.  Nothing showing up in the log related to this.

**Comment by scotty9090** [comment]
Okay, working now.  I'm not sure what was going on, but I tried a vanilla hopper on top and that worked, Then tried all of the ducts / pipes again and those worked as well.  I'll go ahead and close this and will re-open if it happens again.

**Comment by Malorolam** [comment]
There's definitely an issue somewhere, I've noticed it as well, I first thought it was a small TE duct bug but it shows up with other transfer blocks.

**Comment by iaxyz** [comment]
Inserting bags automatically (no matter which way I tried) doesnt work when there're less bags stored then you need for the selected bag tier.
example: Epic Lootbag is selected: If you have 63 or less bags stored it doesnt work. Until you have at least 64 it will work. (I have the problem with my automatic loot bag upgrader)

I hope you can fix it because I love your mod!

**Comment by IamAlathe** [comment]
I had this issue with the bag recycler and a flat item transfer node from AA, bags disappeared from the recycler (number going down) but the number in the storage block did not increase.

**Comment by hron84** [comment]
@IamAlathe just a small correction, flat item transfer nodes are from XU not from AA. Mod name labels not always displayed correctly under 1.1x, this makes confusion sometimes.

Same here btw, Skyblock Adventures pack, latest version, lower tier package must be selected in the storage block to proper counting. If I withdraw too much bags from the block, functionality breaks. Luckily, I have enough bags for ages as I connected a loot recycler to the system too 😄

**Comment by IamAlathe** [comment]
@hron84 You are correct, I was mistaken about the mod the transfer node comes from.  I often play with both mods, so that makes it easier for me to get confused. 😆 And yes, keeping the tier selection within usable bounds does allow automated transfer.

**Comment by hron84** [comment]
The only problem is I cannot control the extraction of the selected bags. There is no comparator output on the storage block, neither have any restriction on the GUI.

**Comment by Malorolam** [comment]
Fixed in 2.5.4
