### ISSUE TITLE
Cannot whitelist mobs with $STARTENTITYLIST

### ISSUE THREAD

**Issue by ReikanFurrow** [Malorolam/LootBags#107]
I am having trouble whitelisting mobs, including those from mods and vanilla. My goal is to make it so that only witches drop a bag which contains alchemical items, but it would seem that every mob is dropping this bag as well. My Config is as follows:

$STARTBAG:lootbagWitch:1
    $ISSECRET:false
    $BAGTEXTCOLOR:$WHITE
    $BAGTEXTUNOPENED:$AQUA:This Bag is Unopened
    $BAGTEXTOPENED:Has been opened
    $BAGTEXTSHIFT:$DROPCHANCES
    $WEIGHT:1000
    $CRAFTEDFROM:$NULL
	$MOBSPAWNWEIGHT:1000
    $USEGENERALLOOTSOURCES:false
    $MAXIMUMITEMS:5
    $MINIMUMITEMS:1
    $MAXIMUMGENERALLOOTWEIGHT:-1
    $MINIMUMGENERALLOOTWEIGHT:-1
    $PREVENTITEMREPEATS:none
	$STARTENTITYLIST
$INTERNALNAME:Witch
	$ENDENTITYLIST
    $EXCLUDEENTITIES:false
	$STARTWHITELIST
		minecraft:soul_sand:0:1:4:5
		minecraft:glowstone:0:1:4:5
		minecraft:nether_wart:0:1:16:20
		minecraft:dye:15:1:6:15
		minecraft:sugar:0:1:16:20
		minecraft:spider_eye:0:1:8:20
		minecraft:fermented_spider_eye:0:1:8:10
		minecraft:blaze_powder:0:1:8:10
		minecraft:magma_cream:0:1:8:10
		minecraft:brewing_stand:0:1:1:2
		minecraft:cauldron:0:1:1:10
		minecraft:speckled_melon:0:1:8:10
		minecraft:fire_charge:0:1:8:10
		minecraft:poisonous_potato:0:1:6:20
		minecraft:golden_carrot:0:1:8:10
		minecraft:quartz:0:1:8:10
		minecraft:redstone:0:1:16:20
		minecraft:slime_ball:0:1:8:10
		minecraft:glowstone_dust:0:1:16:10
		minecraft:potion:0:1:16:30
		minecraft:book:0:1:16:10
		minecraft:blaze_rod:0:1:4:10
		minecraft:string:0:1:1:10
		minecraft:torch:0:1:16:40
		minecraft:golden_apple:0:1:1:10
		minecraft:gold_ingot:0:1:8:30
		minecraft:bucket:0:1:1:20
		minecraft:experience_bottle:0:1:12:10
		minecraft:potion:8193&8198#8200&8202#8204&8206#8225&8226#8228&8229#8232&8234#8236#8257&8260#8262#8264&8266#8268&8270:1:1:10
		Natura:berry:0&3:4:32:40
		TConstruct:heartCanister:1:1:3:10
		confighealth:heartfragment:0:1:3:10
	$ENDWHITELIST
    $STARTBLACKLIST
        lootbags:itemlootbag:0
    $ENDBLACKLIST
$ENDBAG:lootbagWitch

As well, my logs are outputting the following:

[00:20:47] [Client thread/ERROR] [FML]: [LOOTBAGS]: Lootbags !!CONFIG ERROR!!    Unknown text found at line 81: skipping line.
[00:20:47] [Client thread/ERROR] [FML]: [LOOTBAGS]: Lootbags !!CONFIG ERROR!!    Unknown command found at line 82: exiting entity list subroutine.
[00:20:47] [Client thread/ERROR] [FML]: [LOOTBAGS]: Lootbags !!CONFIG ERROR!!    Text at line: 82 is not a command or in a list.  Please only have commands, list components, or whitespace in the config.

Which is where my entitylist is located in my configuration, but as far as I can see its correct, though it's likely I am simply making a mistake. I have exhausted every avenue I could think of to fix this, and searched the closed issues to find answers, but nothing works. If it helps, I am running 1.7.10 as well as forge version 10.13.4.1614-1.7.10. Any help will be appreciated!

**Comment by Malorolam** [comment]
So first issue is you didn't change $EXCLUDEENTITIES:false to true, how you have it is it'll exclude witches from dropping instead of only allowing witches.
I'm not getting that config error, I'd check in notepad++ to see if there's some odd character in there that doesn't show elsewhere.

**Comment by ReikanFurrow** [comment]
Thank you for the prompt response! So I was misinterpreting the use of the $EXCLUDEENTITIES command this whole time... I figured it was definitely something I was doing wrong. I will check and see if when I reverse that if it will work. Also, I believe that the error in the logs is simply an issue with my current setup, as even with the default configuration files, it persists.
