### ISSUE TITLE
Loot Recycler Adding Bags!?

### ISSUE THREAD

**Issue by Nexusdog** [Malorolam/LootBags#109]
It's over 8000 and still counting... I have no idea what is going on or how to stop it!?

**Comment by Nexusdog** [comment]
Sorry, forgot to add

MC/F 1.12.2/2583

**Comment by Malorolam** [comment]
More details are needed, if you had a recycler/opener loop, the earlier default config settings didn't take the increased loot in 1.12 into account and had an infinite growth.  2.4.5 changes the values to not have this happen (refer to the patch notes to see the values without having to delete your lootbags.cfg)
