### ISSUE TITLE
Game won't start with lootbags installed

### ISSUE THREAD

**Issue by Aerbearr** [Malorolam/LootBags#112]
I added the lootbags mod to a mod pack called boundless in 1.10.2. Every time I launch the game it crashes and gives this message:

The game crashed whilst there was a severe problem during mod loading that has caused the game to fail
Error: net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from Loot Bags (lootbags).

When I take the mod out my game works fine. I really like the mod as I have played with it on 1.7.10.
Hopefully, this gets fixed.

**Comment by Malorolam** [comment]
I need a full proper log, otherwise this tells me nothing.
