### ISSUE TITLE
Mod detection?

### ISSUE THREAD

**Issue by Mophise** [Malorolam/LootBags#116]
After looking through your documentation, I was wondering if you would consider adding a way to simplify modpack configuration. Perhaps a creative-only item that could let a user configure loot tables for the bags via a gui that could get the item id dumps, and add them to the lootbag tables properly.

**Comment by Malorolam** [comment]
Short answer, no, not in the way you describe.  
Doing that would ultimately mean a significant amount of effort on my part to add in the item, register it, create the gui, and align the elements correctly.  Then that gui would have to offer options for every field in a bag, including the whitelist and blacklist, which would need handling for the item data, minimum and maximum values, and weight of potentially thousands of items.
As it stands now, there is a command that will create the whitelist information for a single item, leaving only the minimum count, maximum count, and weight to configure.  I can certainly create a variation of that that pulls an entire inventory to speed up the process a bit.

**Comment by Mophise** [comment]
Good to know. I'm not familiar with code, so thanks for that info.
That could definitely help things. Would you be adding that to the 1.10.2 version, or just the latest?

**Comment by Malorolam** [comment]
It depends on how independent it is, between 1.10 and 1.12 I had to rewrite a few sections to work with the changes, so if it's dependent on those I can't guarantee I'll add it to older versions.  I doubt that'll be the case though, the single version didn't have to be reworked.

**Comment by Malorolam** [comment]
Added to 1.12.2-2.5.5.
