### ISSUE TITLE
Black and Pink Lootbag textures

### ISSUE THREAD

**Issue by Arabella667** [Malorolam/LootBags#119]
I have the 2.5.4 Lootbags version and jei on 1.12.2 only and my Lootbag textures are the black and pink boxes. the 3 machines textures and the ancient lootbag textures are fine. i have forge 1.12.2-14.23.2.2624.

**Comment by Malorolam** [comment]
Delete and redownload Lootbags and see if it still happens.

**Comment by Arabella667** [comment]
So i deleted it and redownloaded it again and it is still has messed up textures. :(

**Comment by Malorolam** [comment]
Odd.  Lootbags 2.5.4b and JEI 4.8.5.147 only, correct?

**Comment by Arabella667** [comment]
yes

**Comment by Malorolam** [comment]
Post the two Lootbags config files here.

**Comment by Arabella667** [comment]
hold on i have to convert the file type

**Comment by Arabella667** [comment]
[Lootbags.docx](https://github.com/Malorolam/LootBags/files/1799773/Lootbags.docx)
 
[Lootbags_BagConfig.docx](https://github.com/Malorolam/LootBags/files/1799774/Lootbags_BagConfig.docx)

**Comment by Malorolam** [comment]
You have the old version of the config files, they were changed in 2.5.4.  Delete both config files and run the game again.

**Comment by Arabella667** [comment]
Thank you so much for your help it worked.
