### ISSUE TITLE
Whitelists not working properly?

### ISSUE THREAD

**Issue by FuuNoKamiOka** [Malorolam/LootBags#12]
I've tried to add items to the white list a few times now and it's not working. I've tried adding things that stack and things that don't stack. I did the "lootbags_itemdump", got the list, but things are laid out differently. I can't figure out a way to get them to work. :/ 

[Here is a pastebin of my crash](http://pastebin.com/tj0ANkGS) and below is what I have for my whitelisted section.

> "whitelisted items" {
    # Adding a modid and internal item name to this list will add the item to the Loot Bag drop table.  The entry must be in the form <modid>:<itemname>:<damage>:<min stack size>:<max stack size>:<weighting>:[<nbt data (seriously don't try to make this by hand)> (optional)]  Example to whitelist up to 16 iron ingots with a weight of 50: minecraft:iron_ingot:0:1:16:50.
    S:"Global Whitelist" <
        minecraft:gold_pickaxe:0:1:1:3
        minecraft:gold_sword:0:1:1:3
        minecraft:gold_shovel:0:1:1:3
        minecraft:gold_axe:0:1:1:3
        minecraft:gold_helmet:0:1:1:5
        minecraft:gold_chestplate:0:1:1:5
        minecraft:gold_boots:0:1:1:5
        minecraft:gold_leggings:0:1:1:5
        minecraft:redstone:0:1:7:5
     >
}

**Comment by Malorolam** [comment]
Your item names for the golden items are wrong.  Golden equipment is listed as golden_<item> and you have gold_<item>.  I'll improve the error handling of this so it's clear in the log what's wrong.

**Comment by FuuNoKamiOka** [comment]
Well, I've tried adding other things, too. Would the issue just be with the golden item names?

**Comment by Malorolam** [comment]
Yes, it's crashing at that first item, so once you fix those names everything should work fine.

**Comment by FuuNoKamiOka** [comment]
I fixed the names and it's working now, but I haven't gotten a redstone block. Not sure why, yet.

**Comment by Malorolam** [comment]
I'm pretty sure the name redstone is redstone dust and a redstone block is redstone_block so that's the issue.  Double check in the NEI item.csv dump file though.
