### ISSUE TITLE
1.12.2 - Adding bags to the recycler?

### ISSUE THREAD

**Issue by MoonCutter2B** [Malorolam/LootBags#120]
I guess something has changed because the old way of adding loot bags to the recycler, shift right click, doesn't work for me in 1.12.2.
Could ofc be another mod that is interfering?

**Comment by Malorolam** [comment]
Do you mean trying to recycle the bag itself or dump the contents of the bag in the recycler?
The first only works if the bag is dropped by another bag and it isn't blacklisted in the recycler.

**Comment by MoonCutter2B** [comment]
Stupid me, I was used to how I thought it worked in 1.7.10 and stuff has changed.
