### ISSUE TITLE
Bag Storage bug?

### ISSUE THREAD

**Issue by JoeSGT** [Malorolam/LootBags#121]
Hello the version i am using are
```
Lootbags - 1.12.2-2.5.4b
Forge - 1.12.2-14.23.2.2624
```
and my issue is with the bag Storage it seem you have get pretty much any items out of it
here how i reduce it
1) get an loot bag 
2) place down the bag storage
3) right click your loot bag and take 1 item 
4) put the loot bag into bag storage on to the first slot into the `Storage:`
5) take out the look bag out of the slot that say `Needed:` right click your bag and you end up with random items in it

**Comment by Malorolam** [comment]
Not a bug, correct behaviour when 
`B:"Prevent Merging Opened Bags"=false`
in lootbags.cfg

**Comment by JoeSGT** [comment]
Thanks you
