### ISSUE TITLE
Missing textures 1.7.10 final

### ISSUE THREAD

**Issue by MRxP1ZZ4** [Malorolam/LootBags#123]
I am playing the ultimate ninja mudpack by the true ginger shadow so I'm not sure if there are conflicting mods but, whenever I get a bag they have a purple and black Checker and don't open a bag when I try to open it it just disapears

**Comment by Malorolam** [comment]
Something likely got messed up with the configs when installing the pack.  Did the bags have normal names or something like name.lootbags_lootbag_something.name?

**Comment by speggitighti** [comment]
having the same problem, not sure what config you deleted though..

**Comment by Malorolam** [comment]
Texture issues are usually the cause of a corrupted Lootbags_BagConfig.cfg.  Deleting this file and allowing it to regenerate (or redownloading it if it's customized from a pack or server) will fix the issue 95% of the time.
