### ISSUE TITLE
custom loot bag

### ISSUE THREAD

**Issue by TheNimbleNinja** [Malorolam/LootBags#126]
i cant make a custom texture for the loot bag i tried everything to get the texture to work. i dont know what to name the texture, json file and the info in the json file. im not good with written documents and there is litterly no vido tutorial out there for making custom loot bags. also im using resource loader to load the textures of the custom loot bags. cna you help me to get it working?

**Comment by Malorolam** [comment]
So for the bags there's the internal name of the bag used in 
`$STARTBAG:lootbag_Common:0` which governs the core bit that changes.  So in this case it's lootbag_Common.

Going from there, the texture is named <internal name in all lowercase>_item_texture.png, so lootbag_common_item_texture.png.  This is just convention at this point as the .jsons will handle properly pointing to the right texture.  The model .json file is called <internal name in all lowercase>.json, so lootbag_common.json.  In it is just:
`{`
`    "parent": "builtin/generated",`
`    "textures": {`
`        "layer0": "lootbags:items/<texture name without the extension>"`
`    }
`}`
so in this case it's just
`{`
`    "parent": "builtin/generated",`
`    "textures": {`
`        "layer0": "lootbags:items/lootbag_common_item_texture"`
`    }
`}`

Finally is the .lang file, which the lootbag entries are in the form name.lootbags_<internal lootbag name as written in Lootbags_BagConfig.cfg>.name=<whatever the name is supposed to be>, so it should look like:
name.lootbags_lootbag_Common.name=Common Lootbag
All these new files are then packaged into a Resource Pack and loaded just like you would a texture pack in Minecraft.  I can't guarantee using a mod to handle this for you will work, I've never tested it.

This is how you go about creating the resources needed for an entirely new bag.  There is a shortcut on the texture and .json side if you're going for just a coloured variation of my bag texture, which is to use the $BAGCOLOR command, the Patient or Direwolf bags have examples of how this works with more detail in the wiki here.

**Comment by TheNimbleNinja** [comment]
i still couldnt figure out how to make the texture for the custom loot bag to work useing resource loader. the lang file worked but the texture didnt and i dont know if ive done it wrong or it doesnt work with resource loader
but thanks for the help

**Comment by TheNimbleNinja** [comment]
also no on has done a video tutorial on making custom loot bags for ur mod and that makes me sad :(
