### ISSUE TITLE
LOOTBags indicating Disabled & Nothing in Loot Table*****

### ISSUE THREAD

**Issue by PorterGames** [Malorolam/LootBags#128]
[Lootbags_BagConfig.cfg.txt](https://github.com/Malorolam/LootBags/files/2005427/Lootbags_BagConfig.cfg.txt)
![screenshot_1](https://user-images.githubusercontent.com/39307108/40064342-4db96592-582d-11e8-9acc-c14fe322d0d7.png)

**Comment by PorterGames** [comment]
Sorry this is for 1.12.2

**Comment by Malorolam** [comment]
You are using an old config, delete the two lootbags config files and let them build again.  That should fix everything.

**Comment by Malorolam** [comment]
The config files for every mod are in the configs folder in the base folder for that instance.  So you have the mods folder where all the mod .jars go, if you go up one folder, there'll be a folder called config if you've run that instance at least once, in there the files I'm referring to are lootbags.cfg and Lootbags_BagConfig.cfg.
If you're using the Twitch launcher for your modded instances, you can get to that base folder by clicking the ... button on the right side of the Minecraft instance screen and selecting Open Folder.

**Comment by zxf925487662** [comment]
1.12.2 version I am the same problem, and after using your method, the problem still exists.
I'm sorry, I can't speak English well.
