### ISSUE TITLE
Mod Crashed with Forge 1.12.2-14.23.3.2698 [LootBags-1.12.2-2.5.4b]

### ISSUE THREAD

**Issue by fandomaniac** [Malorolam/LootBags#129]
Here's the crash report:

Description: There was a severe problem during mod loading that has caused the game to fail

net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from Loot Bags (lootbags)
Caused by: java.lang.VerifyError: Inconsistent stackmap frames at branch target 47
Exception Details:
  Location:
    net/minecraft/world/World.func_175638_a(Lnet/minecraft/util/math/BlockPos;Lnet/minecraft/world/EnumSkyBlock;)I @32: goto
  Reason:
    Current frame's stack size doesn't match stackmap.
  Current Frame:
    bci: @32
    flags: { }
    locals: { 'net/minecraft/world/World', 'net/minecraft/util/math/BlockPos', 'net/minecraft/world/EnumSkyBlock', 'net/minecraft/block/state/IBlockState' }
    stack: { integer }
  Stackmap Frame:
    bci: @47
    flags: { }
    locals: { 'net/minecraft/world/World', 'net/minecraft/util/math/BlockPos', 'net/minecraft/world/EnumSkyBlock', 'net/minecraft/block/state/IBlockState' }
    stack: { top, integer }
  Bytecode:
    0x0000000: 2cb2 0284 a600 0e2a 2bb6 0308 9900 0610
    0x0000010: 0fac 2a2b b601 854e 2cb2 0284 a600 0703
    0x0000020: a700 0f2d b901 9501 002d 2a2b b808 7236
    0x0000030: 042d b901 9501 002d 2a2b b603 0b36 0515
    0x0000040: 0504 a200 0604 3605 1505 100f a100 0615
    0x0000050: 04ac 1504 100e a100 0615 04ac b804 d33a
    0x0000060: 06b8 0876 3a07 1907 be36 0803 3609 1509
    0x0000070: 1508 a200 4a19 0715 0932 3a0a 1906 2bb6
    0x0000080: 087a 190a b608 7e57 2a2c 1906 b603 4115
    0x0000090: 0564 360b 150b 1504 a400 0715 0b36 0415
    0x00000a0: 0410 0ea1 0013 1504 360c 150c 360d 1906
    0x00000b0: b604 de15 0dac 8409 01a7 ffb5 1504 3607
    0x00000c0: 1906 b604 de15 07ac 3a0e 1906 b604 de19
    0x00000d0: 0ebf                                   
  Exception Handler Table:
    bci [97, 174] => handler: 200
    bci [182, 192] => handler: 200
    bci [200, 202] => handler: 200
  Stackmap Table:
    same_frame(@18)
    append_frame(@35,Object[#401])
    full_frame(@47,{Object[#2],Object[#24],Object[#640],Object[#401]},{Top,Integer})
    full_frame(@72,{Object[#2],Object[#24],Object[#640],Object[#401],Integer,Integer},{Top})
    same_locals_1_stack_item_frame(@82,Top)
    same_locals_1_stack_item_frame(@92,Top)
    full_frame(@110,{Object[#2],Object[#24],Object[#640],Object[#401],Integer,Integer,Object[#22],Object[#2177],Integer,Integer},{Top})
    full_frame(@159,{Object[#2],Object[#24],Object[#640],Object[#401],Integer,Integer,Object[#22],Object[#2177],Integer,Integer,Object[#686],Integer},{Top})
    same_locals_1_stack_item_frame(@182,Top)
    full_frame(@188,{Object[#2],Object[#24],Object[#640],Object[#401],Integer,Integer,Object[#22],Object[#2177],Integer,Integer},{Top})
    full_frame(@200,{Object[#2],Object[#24],Object[#640],Object[#401],Integer,Integer,Object[#22]},{Object[#274]})

	at mal.lootbags.LootbagsUtil.getLootManager(LootbagsUtil.java:276)
	at mal.lootbags.loot.LootMap.setContext(LootMap.java:510)
	at mal.lootbags.LootBags.postInit(LootBags.java:212)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraftforge.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:627)
	at sun.reflect.GeneratedMethodAccessor2.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
	at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:218)
	at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:196)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
	at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:135)
	at net.minecraftforge.fml.common.Loader.initializeMods(Loader.java:749)
	at net.minecraftforge.fml.client.FMLClientHandler.finishMinecraftLoading(FMLClientHandler.java:329)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:534)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:377)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_171, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 4258960872 bytes (4061 MB) / 7516192768 bytes (7168 MB) up to 7516192768 bytes (7168 MB)
	JVM Flags: 5 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xms7168m -Xmx7168m -XX:+UseG1GC -XX:MaxGCPauseMillis=4
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP 9.42 Powered by Forge 14.23.3.2698 83 mods loaded, 83 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State  | ID                          | Version              | Source                                          | Signature                                |
	|:------ |:--------------------------- |:-------------------- |:----------------------------------------------- |:---------------------------------------- |
	| UCHIJ  | minecraft                   | 1.12.2               | minecraft.jar                                   | None                                     |
	| UCHIJ  | mcp                         | 9.42                 | minecraft.jar                                   | None                                     |
	| UCHIJ  | FML                         | 8.0.99.99            | modpack.jar                                     | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| UCHIJ  | forge                       | 14.23.3.2698         | modpack.jar                                     | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| UCHIJ  | openmodscore                | 0.11.5               | minecraft.jar                                   | None                                     |
	| UCHIJ  | obfuscate                   | 0.2.4                | minecraft.jar                                   | None                                     |
	| UCHIJ  | quark                       | r1.4-123             | Quark-r1.4-123.jar                              | None                                     |
	| UCHIJ  | autoreglib                  | 1.3-17               | AutoRegLib-1.3-17.jar                           | None                                     |
	| UCHIJ  | backpacks16840              | 3.5.0                | backpacks 1.12.2 - 3.5.0.jar                    | None                                     |
	| UCHIJ  | bibliocraft                 | 2.4.3                | BiblioCraft[v2.4.3][MC1.12.0].jar               | None                                     |
	| UCHIJ  | chameleon                   | 1.12-4.1.3           | Chameleon-1.12-4.1.3.jar                        | None                                     |
	| UCHIJ  | chesttransporter            | 2.8.8                | ChestTransporter-1.12.2-2.8.8.jar               | None                                     |
	| UCHIJ  | cjcm                        | 1.0                  | cjcm-1.0.jar                                    | None                                     |
	| UCHIJ  | codechickenlib              | 3.1.8.341            | CodeChickenLib-1.12.2-3.1.8.341-universal.jar   | f1850c39b2516232a2108a7bd84d1cb5df93b261 |
	| UCHIJ  | cookingforblockheads        | 6.3.26               | CookingForBlockheads_1.12.2-6.3.26.jar          | None                                     |
	| UCHIJ  | craftablesaddles            | 1.3                  | Craftable+Saddles[1.12]-1.3.jar                 | None                                     |
	| UCHIJ  | ptrmodellib                 | 1.0.2                | PTRLib-1.0.2.jar                                | None                                     |
	| UCHIJ  | props                       | 2.6.0                | Decocraft-2.6.0_1.12.2.jar                      | None                                     |
	| UCHIJ  | cdm                         | 0.3.1                | device-mod-0.3.1-1.12.2.jar                     | None                                     |
	| UCHIJ  | dungeontactics              | DT-0.14.2            | DungeonTactics-1.12.2-0.14.2.jar                | None                                     |
	| UCHIJ  | dynamiclights               | 1.4.8                | DynamicLights-1.12.2.jar                        | None                                     |
	| UCHIJ  | dynamiclights_onfire        | 1.0.7                | DynamicLights-1.12.2.jar                        | None                                     |
	| UCHIJ  | dynamiclights_creepers      | 1.0.6                | DynamicLights-1.12.2.jar                        | None                                     |
	| UCHIJ  | dynamiclights_dropitems     | 1.1.0                | DynamicLights-1.12.2.jar                        | None                                     |
	| UCHIJ  | dynamiclights_entityclasses | 1.0.1                | DynamicLights-1.12.2.jar                        | None                                     |
	| UCHIJ  | dynamiclights_mobequipment  | 1.1.0                | DynamicLights-1.12.2.jar                        | None                                     |
	| UCHIJ  | dynamiclights_flamearrows   | 1.0.1                | DynamicLights-1.12.2.jar                        | None                                     |
	| UCHIJ  | dynamiclights_floodlights   | 1.0.3                | DynamicLights-1.12.2.jar                        | None                                     |
	| UCHIJ  | dynamiclights_otherplayers  | 1.0.9                | DynamicLights-1.12.2.jar                        | None                                     |
	| UCHIJ  | dynamiclights_theplayer     | 1.1.3                | DynamicLights-1.12.2.jar                        | None                                     |
	| UCHIJ  | fastleafdecay               | v14                  | FastLeafDecay-v14.jar                           | None                                     |
	| UCHIJ  | foamflower                  | 1.12.2-1.0.0.0-beta1 | foamflower-1.12.2-1.0.0.0-beta1.jar             | None                                     |
	| UCHIJ  | cfm                         | 4.2.0                | furniture-4.2.0-1.12.2.jar                      | None                                     |
	| UCHIJ  | gravestone                  | 1.10.1               | gravestone-1.10.1.jar                           | None                                     |
	| UCHIJ  | waila                       | 1.8.24               | Hwyla-1.8.24-B39_1.12.jar                       | None                                     |
	| UCHIJ  | infernalmobs                | 1.7.5                | InfernalMobs-1.12.2.jar                         | None                                     |
	| UCHIJ  | lunatriuscore               | 1.2.0.42             | LunatriusCore-1.12.2-1.2.0.42-universal.jar     | None                                     |
	| UCHIJ  | ingameinfoxml               | 2.8.2.94             | InGameInfoXML-1.12.2-2.8.2.94-universal.jar     | None                                     |
	| UCHIJ  | ironchest                   | 1.12.2-7.0.40.824    | ironchest-1.12.2-7.0.40.824.jar                 | None                                     |
	| UCHIJ  | jei                         | 4.9.1.179            | jei_1.12.2-4.9.1.179.jar                        | None                                     |
	| UCHIJ  | jrftl                       | 1.1                  | JRFTL[1.12.2]-1.1.jar                           | None                                     |
	| UCHIEE | lootbags                    | 2.5.4b               | LootBags-1.12.2-2.5.4b.jar                      | None                                     |
	| UCHI   | lycanitesmobs               | 1.20.2.2 - MC 1.12.2 | LycanitesMobsComplete 1.20.2.2 [1.12.2]-1.0.jar | None                                     |
	| UCHI   | arcticmobs                  | 1.20.2.2 - MC 1.12.2 | LycanitesMobsComplete 1.20.2.2 [1.12.2]-1.0.jar | None                                     |
	| UCHI   | demonmobs                   | 1.20.2.2 - MC 1.12.2 | LycanitesMobsComplete 1.20.2.2 [1.12.2]-1.0.jar | None                                     |
	| UCHI   | desertmobs                  | 1.20.2.2 - MC 1.12.2 | LycanitesMobsComplete 1.20.2.2 [1.12.2]-1.0.jar | None                                     |
	| UCHI   | elementalmobs               | 1.20.2.2 - MC 1.12.2 | LycanitesMobsComplete 1.20.2.2 [1.12.2]-1.0.jar | None                                     |
	| UCHI   | forestmobs                  | 1.20.2.2 - MC 1.12.2 | LycanitesMobsComplete 1.20.2.2 [1.12.2]-1.0.jar | None                                     |
	| UCHI   | freshwatermobs              | 1.20.2.2 - MC 1.12.2 | LycanitesMobsComplete 1.20.2.2 [1.12.2]-1.0.jar | None                                     |
	| UCHI   | infernomobs                 | 1.20.2.2 - MC 1.12.2 | LycanitesMobsComplete 1.20.2.2 [1.12.2]-1.0.jar | None                                     |
	| UCHI   | junglemobs                  | 1.20.2.2 - MC 1.12.2 | LycanitesMobsComplete 1.20.2.2 [1.12.2]-1.0.jar | None                                     |
	| UCHI   | mountainmobs                | 1.20.2.2 - MC 1.12.2 | LycanitesMobsComplete 1.20.2.2 [1.12.2]-1.0.jar | None                                     |
	| UCHI   | plainsmobs                  | 1.20.2.2 - MC 1.12.2 | LycanitesMobsComplete 1.20.2.2 [1.12.2]-1.0.jar | None                                     |
	| UCHI   | saltwatermobs               | 1.20.2.2 - MC 1.12.2 | LycanitesMobsComplete 1.20.2.2 [1.12.2]-1.0.jar | None                                     |
	| UCHI   | shadowmobs                  | 1.20.2.2 - MC 1.12.2 | LycanitesMobsComplete 1.20.2.2 [1.12.2]-1.0.jar | None                                     |
	| UCHI   | swampmobs                   | 1.20.2.2 - MC 1.12.2 | LycanitesMobsComplete 1.20.2.2 [1.12.2]-1.0.jar | None                                     |
	| UCHI   | malisiscore                 | 1.12.2-6.4.0         | malisiscore-1.12.2-6.4.0.jar                    | None                                     |
	| UCHI   | malisisblocks               | 1.12.2-6.1.0         | malisisblocks-1.12.2-6.1.0.jar                  | None                                     |
	| UCHI   | malisisdoors                | 1.12.2-7.3.0         | malisisdoors-1.12.2-7.3.0.jar                   | None                                     |
	| UCHI   | mantle                      | 1.12-1.3.2.24        | Mantle-1.12-1.3.2.24.jar                        | None                                     |
	| UCHI   | mapwriter                   | 2.8.2                | MapWriter-1.12.2-2.8.2.jar                      | None                                     |
	| UCHI   | natura                      | 1.12.2-4.3.2.49      | natura-1.12.2-4.3.2.49.jar                      | None                                     |
	| UCHI   | nex                         | 2.1.14.15            | NetherEx-1.12-2.1.14.15.jar                     | None                                     |
	| UCHI   | recipehandler               | 0.10                 | NoMoreRecipeConflict-0.10(1.12.2).jar           | None                                     |
	| UCHI   | nei                         | 2.4.1                | NotEnoughItems-1.12.2-2.4.1.233-universal.jar   | f1850c39b2516232a2108a7bd84d1cb5df93b261 |
	| UCHI   | openmods                    | 0.11.5               | OpenModsLib-1.12.2-0.11.5.jar                   | d2a9a8e8440196e26a268d1f3ddc01b2e9c572a5 |
	| UCHI   | openblocks                  | 1.7.6                | OpenBlocks-1.12.2-1.7.6.jar                     | d2a9a8e8440196e26a268d1f3ddc01b2e9c572a5 |
	| UCHI   | guilib                      | $version             | paintingselgui-PSG+Revamed-1.12.2-1.1.0.1.jar   | None                                     |
	| UCHI   | paintingselgui              | $version             | paintingselgui-PSG+Revamed-1.12.2-1.1.0.1.jar   | None                                     |
	| UCHI   | harvestcraft                | 1.12.2u              | Pam's HarvestCraft 1.12.2u.jar                  | None                                     |
	| UCHI   | roguelike                   | 1.8.0                | RoguelikeDungeons-1.12.2-1.8.0.jar              | None                                     |
	| UCHI   | simplecore                  | 1.6.0.6              | simplecore-1.12.2-1.6.0.6.jar                   | None                                     |
	| UCHI   | simpleores                  | 1.11.1.9             | simpleores-1.12.2-1.11.1.9.jar                  | None                                     |
	| UCHI   | simplyenchanting            | 1.0.3                | SimplyEnchanting-1.12-1.0.3.jar                 | None                                     |
	| UCHI   | soccer                      | 1.0                  | soccer-mod-1.0-1.12.2.jar                       | None                                     |
	| UCHI   | storagedrawers              | 1.12-5.3.5           | StorageDrawers-1.12.2-5.3.6.jar                 | None                                     |
	| UCHI   | tconstruct                  | 1.12.2-2.9.1.65      | TConstruct-1.12.2-2.9.1.65.jar                  | None                                     |
	| UCHI   | torohealthmod               | 1.12.2-11            | torohealth-1.12.2-11.jar                        | None                                     |
	| UCHI   | treechopper                 | 1.2.4                | TreeChopper-1.12.2-1.2.4.jar                    | None                                     |
	| UCHI   | vehicle                     | 0.9.0                | vehicle-0.9.0-mc1.12.2.jar                      | None                                     |
	| UCHI   | vending                     | 1.12.2-3.0.1.1       | vending-1.12.2-3.0.1.1.jar                      | None                                     |
	| UCHI   | wailaharvestability         | 1.1.12               | WailaHarvestability-mc1.12-1.1.12.jar           | None                                     |
	| UCHI   | waystones                   | 4.0.43               | Waystones_1.12.2-4.0.43.jar                     | None                                     |

	Loaded coremods (and transformers): 
MalisisCorePlugin (malisiscore-1.12.2-6.4.0.jar)
  
BCModPlugin (backpacks 1.12.2 - 3.5.0.jar)
  brad16840.core.ClassTransformer
OpenModsCorePlugin (OpenModsLib-1.12.2-0.11.5.jar)
  openmods.core.OpenModsClassTransformer
LoadingPlugin (Quark-r1.4-123.jar)
  vazkii.quark.base.asm.ClassTransformer
DLFMLCorePlugin (DynamicLights-1.12.2.jar)
  atomicstryker.dynamiclights.common.DLTransformer
ObfuscatePlugin (obfuscate-0.2.4-1.12.2.jar)
  com.mrcrayfish.obfuscate.asm.ObfuscateTransformer
	GL info: ' Vendor: 'ATI Technologies Inc.' Version: '4.5.13474 Compatibility Profile Context 22.19.159.256' Renderer: 'Radeon(TM) RX 580'
	OpenModsLib class transformers: [llama_null_fix:FINISHED],[horse_base_null_fix:FINISHED],[pre_world_render_hook:FINISHED],[player_render_hook:FINISHED],[horse_null_fix:FINISHED]
	Pulsar/natura loaded Pulses: 
		- NaturaCommons (Enabled/Forced)
		- NaturaOverworld (Enabled/Not Forced)
		- NaturaNether (Enabled/Not Forced)
		- NaturaDecorative (Enabled/Not Forced)
		- NaturaTools (Enabled/Not Forced)
		- NaturaEntities (Enabled/Not Forced)
		- NaturaOredict (Enabled/Forced)
		- NaturaWorld (Enabled/Not Forced)

	Pulsar/tconstruct loaded Pulses: 
		- TinkerCommons (Enabled/Forced)
		- TinkerWorld (Enabled/Not Forced)
		- TinkerTools (Enabled/Not Forced)
		- TinkerHarvestTools (Enabled/Forced)
		- TinkerMeleeWeapons (Enabled/Forced)
		- TinkerRangedWeapons (Enabled/Forced)
		- TinkerModifiers (Enabled/Forced)
		- TinkerSmeltery (Enabled/Not Forced)
		- TinkerGadgets (Enabled/Not Forced)
		- TinkerOredict (Enabled/Forced)
		- TinkerIntegration (Enabled/Forced)
		- TinkerFluids (Enabled/Forced)
		- TinkerMaterials (Enabled/Forced)
		- TinkerModelRegister (Enabled/Forced)
		- wailaIntegration (Enabled/Not Forced)

**Comment by Malorolam** [comment]
It's definitely to do with Dynamic Lights.  I can't tell yet if it's something they're doing odd or I just didn't take something into account with my fake world.
The reason it's breaking now is it seems Forge upped the aggressiveness of some of the error handling recently.

**Comment by fandomaniac** [comment]
You were right. Dynamic Lights was updated and the Minecraft client is no longer crashing. Thanks, @Malorolam

**Comment by Vamille** [comment]
@fandomaniac @Malorolam Help i got the same problem i want to play with Lootbag but it crash same like ur's fandomaniac how to fix it?

**Comment by Malorolam** [comment]
Update Dynamic Lights and it fixes the problem.
