### ISSUE TITLE
Sorting Issue

### ISSUE THREAD

**Issue by McNutty145** [Malorolam/LootBags#13]
I was storing loot bags in an Extra Utilities filing cabinet. Unopened bags stacked and opened ones did not, as expected. I was opening bags to look for a specific item and putting the bags that did not contain it back in the cabinet to deal with later. After finding the item and taking it out of the bag, I placed the bag back in the cabinet. My client and the server immediately crashed. There was only one filing cabinet in the world, which contained several bags.

[crash-2016-04-07_15.56.23-client.txt](https://github.com/Malorolam/LootBags/files/209409/crash-2016-04-07_15.56.23-client.txt)

**Comment by Malorolam** [comment]
Update Lootbags to the latest version and see if the issue persists.

**Comment by McNutty145** [comment]
As much as I don't want to be a pain about this, there are a few problems with that. First, I don't own the relevant server. Second, I was able to get back on, and the issue did not reoccur. I was also unable to recreate it in a single-player world.

Sorry about that.
