### ISSUE TITLE
Suggestion: Add forge version dependency

### ISSUE THREAD

**Issue by cryxli** [Malorolam/LootBags#132]
**Setup**

- Loot  Bags: 1.5.5
- Forge: 1.12.2-14.23.2.2654

**Observation**

Loot Bags crashes the client with a NoSuchMethod:

[crash-2018-05-27_12.37.54-client.txt](https://github.com/Malorolam/LootBags/files/2042529/crash-2018-05-27_12.37.54-client.txt)

I haven't reduced to case to the bare minimum number of mods. But since the line in question looks like an ordinary registry call, I'd suggest adding a reference to the ```mcmod.info``` with a minimum forge requirement. Like this:

    "dependencies": ["Forge@[14.23.2.2654,)"]

This reads as forge has to be present at least in version 14.23.2.2654. If the forge version is newer, it'll work, too.

**Comment by Malorolam** [comment]
Will be fixed in the next version.
