### ISSUE TITLE
My Server crashes while trying to load lootbags

### ISSUE THREAD

**Issue by aaronegger** [Malorolam/LootBags#133]
Hey :)

I tried to use this mod for my server (1.12.2 Forge 14.23.3.2655), but i wont start..

Output from the server: https://gist.github.com/aaronegger/1eeb783a0ae7bc8062a38d697c4bcf96
Exception: java.lang.NoSuchMethodError: net.minecraftforge.fml.common.registry.GameRegistry.registerTileEntity(Ljava/lang/Class;Lnet/minecraft/util/ResourceLocation;)V

Do you have any idea how to fix this?

**Comment by Malorolam** [comment]
Update Forge.

**Comment by aaronegger** [comment]
Ok updating forge fixed the issue.
But sadly i am fixed to 2703 cause of sponge and this version is buggy :(
But maybe in some days i am able to use this mod :)
