### ISSUE TITLE
Loot bags not having textures in 1.12.2

### ISSUE THREAD

**Issue by gman4161** [Malorolam/LootBags#134]
I have the latest editions of forge and the Loot Bag mod for 1.12.2 but the loot bags are just purple/black squares and the names are "name.lootbag_lootbaglegendary.name"(where legendary is the rarity). I have literally no other mods as I removed them thinking they were causing the issue but it persisted.
In short, no loot bag textures(except for the artifact loot bag[also has messed up name] and the blocks[working as intended]). That's about it.

**Comment by Malorolam** [comment]
Delete the two lootbags configs and run the game again.

**Comment by gman4161** [comment]
Thanks! All better.
