### ISSUE TITLE
[1.12.2] unnecessary files in the jar file

### ISSUE THREAD

**Issue by KorDum** [Malorolam/LootBags#136]
![image](https://user-images.githubusercontent.com/1331559/41191471-b5a6bfa4-6bf8-11e8-89bd-5ccf6cb98757.png)

**Comment by Malorolam** [comment]
Whoops, remade my build file recently and must have missed those.  Later versions will exclude those properly.

**Comment by KorDum** [comment]
:) Thanks for mod!
