### ISSUE TITLE
Shown name in JEI for new created LBs 

### ISSUE THREAD

**Issue by tomorrow4268** [Malorolam/LootBags#138]
Since it was written in the wiki, i was wondering where i can find that .lang file. Couldn't find it and so was not capable to add custom lootbags that have nice names as description without that "name.xxxx.name" pre-&suffixes.

Thx in advance

using LootBags-1.11.2-2.4.3.jar

**Comment by tomorrow4268** [comment]
since i am also using llibrary for jurassicraft i hope both .lang files are not affecting each other.

**Comment by Malorolam** [comment]
You make one yourself with all the unlocalized names of the new bags and their translations, package that into a resource pack, and load it.
https://minecraft.gamepedia.com/Tutorials/Creating_a_resource_pack will get you about 90% of the way there.  It doesn't say clearly, but you can merge/replace .lang files like you can everything else.  The file structure for my .lang files is assets/lootbags/lang/en_us.lang

**Comment by Malorolam** [comment]
I tested it in 1.12.2 before posting that, I know it still works fine.  Make sure the pack.mcmeta file has the correct pack_format number in it for 1.11 and that the .lang file has things listed the correct way, they should look like:
`name.lootbags_lootbag_Derp.name=Derp Bag`
