### ISSUE TITLE
in 1.12.2 lootbags dont work 

### ISSUE THREAD

**Issue by dodobrazil** [Malorolam/LootBags#141]
İ have  downloaded modern skyblock 2 and there weren t lootbags mode that i prefer all the time.I tried to add it on twitch m.c and it crushed all the time when i try to open the game.HELP!!!!(I downloaded more mods and they worked) -----------------------------------------------------------------------------------------------------------------------------------------crush code:The game crashed whilst there was a severe problem during mod loading that has caused the game to fail
The game crashed whilst there was a severe problem during mod loading that has caused the game to fail
Error: net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from Loot Bags (lootbags)

**Comment by Malorolam** [comment]
Modern Skyblock 2 is a 1.11.2 pack, so you need to use the 1.11.2 version of Lootbags, not the 1.12.2 version.
If you mean Modern Skyblock 3, it already has Lootbags in it.

Also, post the entire crash log, not just the first couple of lines, otherwise I can't help with it.
