### ISSUE TITLE
[1.12.2] What happened to inventory depositing?

### ISSUE THREAD

**Issue by Andronomos** [Malorolam/LootBags#142]
In previous versions you used to be able to <kbd>SHIFT</kbd>+Right Click on an inventory to deposit the loot from a bag into it. This was a very useful feature for opening lots of bags and organizing the loot quickly.

Just curious why this feature was removed and if maybe it could come back?

**Comment by Malorolam** [comment]
That was fixed in 2.5.7.

**Comment by Andronomos** [comment]
Ah, okay. I hadn't played much this month. I just knew I've been meaning to post here about it and figured I'd do it today.

Thanks for fixing it :)

**Comment by Andronomos** [comment]
I tried the update yesterday an had an issue, not everything was deposited into the chest. It left an ingot from ThermalExpansion and another item I can't remember the name of.

Are there any limitations with the code or did I discover a bug?

**Comment by Andronomos** [comment]
Seems to have been a fluke. I just tested all bag tiers again on a vanilla and modded chest and it worked perfectly.
