### ISSUE TITLE
Duplication bug

### ISSUE THREAD

**Issue by JoeSGT** [Malorolam/LootBags#143]
The version i am using is 
- LootBags - 1.12.2-2.5.7
- Forge - 14.23.4.2705

You can only do this on a server, I tried doing this on a clean no other mods but Lootbags mod on my clean Forge Server here are the step that i did do attempt to duplication the items that are inside of any bags

1) grab a bag and right click to see what in there but don't click/grab anything yet
2) look up at the sky reason is you don't want to right click any other blocks
3) Right click and Drop the bag at the same time then the GUI will stay open and then you can take the items out of the bag
4) pick up the bag you drop and the items are also in there as you can take them also 

there you go you can dupe easy on a server not singleplayer

**Comment by Malorolam** [comment]
Next major version should fix it.

**Comment by JoeSGT** [comment]
I guess I'll rollback a few version that it doesn't happen on
