### ISSUE TITLE
Drop rate

### ISSUE THREAD

**Issue by minakitty** [Malorolam/LootBags#144]
Not so much a bug as a documentation question.  How do I drop the overall drop rate of loot bags?  On my server, bags seem to drop about the same as vanilla monster drops, when I'm hoping for something more of a special surprise.  Especially when you get into mob grinders for other mods, I've literally seen someone with chests and chests full of the exact same item they've gotten just from loot bags.  I think I want to drop the rate to about 1% of what it is now (so if it's normally 5%, then making it .05%)

**Comment by Malorolam** [comment]
Bag drop chances work off an x/y ratio.  For bag drop rates, there's two config entries that apply to it.  In lootbags.cfg, there is     I:"1 Weighting Resolution"=, which is the y and in Lootbags_BagConfig.cfg for each bag there are $PASSIVESPAWNWEIGHT, $PLAYERSPAWNWEIGHT, $MOBSPAWNWEIGHT, and $BOSSSPAWNWEIGHT, which is the x depending on the situation.  The wiki here goes into more detail about what each one applies to.  
The easiest way to make all bags rarer (or more common) across the board is to increase (or decrease) the weighting resolution by some multiple, so in your case you'd take whatever value is there and multiply it by 100.
