### ISSUE TITLE
lootbags.zs file not working when trying to disable the lootbag container and make shapeless crafting like in 1.10.2

### ISSUE THREAD

**Issue by raziel23x** [Malorolam/LootBags#146]
Here is part of the script for use with the new 1.12.2 to add back in the old shapeless crafting but when the script loads i get errors saying that it cant find the given objects

am i using the wrong meta data for the bags to add them to the shapeless crafting and or how will i find the correct ones to be able to make a working script
//LootBags
recipes.addshapeless(<lootbags:lootbag:1>,[<lootbags:lootbag> * 4]);
recipes.addshapeless(<lootbags:lootbag:2>,[<lootbags:lootbag:1> * 4]);
recipes.addshapeless(<lootbags:lootbag:3>,[<lootbags:lootbag:2> * 4]);
recipes.addshapeless(<lootbags:lootbag:4>,[<lootbags:lootbag:3> * 4]);

Here are my config files just in case you need them
[lootbagconfigfiles.zip](https://github.com/Malorolam/LootBags/files/2328608/lootbagconfigfiles.zip)

**Comment by Malorolam** [comment]
Dunno how I missed this issue, hopefully you solved it yourself.
I have no idea how to use that scripting system, but assuming the format is modid:itemname:metadata, then the metadatas are all wrong, the Lootbags_BagConfig.cfg file will have the itemnames for each specific bag under the $STARTBAG command.

**Comment by raziel23x** [comment]
Never got it to work and I did use the config to use though id's
