### ISSUE TITLE
Loot bags are in every tab in the creative menu

### ISSUE THREAD

**Issue by Rambut** [Malorolam/LootBags#147]
Every loot bag is every tab in the creative menu

Using the latest version of loot bags 1.12.2
Using forge 1.12.2 - 14.23.4.2759

Please fix thank you.

**Comment by Malorolam** [comment]
You are clearly not using the latest version then or another mod is causing the issue, as that bug was fixed in 1.12.2-2.5.2, almost a year ago.  Confirmed with forge version -.2759 to still be working.
