### ISSUE TITLE
AdvancedLightsabers-1.7.10-1.0.4

### ISSUE THREAD

**Issue by SvEgiiVEteR** [Malorolam/LootBags#15]
server
https://gist.github.com/8e31515016720ffaaee560ea3d98b030
it seems the conflict
configs tried to delete but does not help.
del AdvancedLightsabers-1.7.10-1.0.4 all ok

**Comment by Malorolam** [comment]
It looks like an Advanced Lightsabers issue, the lootbags code is only passing an instance of Random, but what's breaking is AL's crystal color list.

**Comment by FiskFille** [comment]
This issue has been fixed in version 1.0.5 of Advanced Lightsabers.
