### ISSUE TITLE
Changing bag type with Recycler

### ISSUE THREAD

**Issue by yar123** [Malorolam/LootBags#151]
How do you change the output bag type with the recycler?

**Comment by Malorolam** [comment]
In the lootbags.cfg file there is a field called
`    I:"Bag ID used in Recycler"=0`
change that number to the ID of the bag you want.

**Comment by yar123** [comment]
Is this server side or client side? Description of modpack says there's supposed to be a GUI button to change the bag type?

**Comment by yar123** [comment]
I've changed the value in the cfg both server and client side to 4 (epic) and the bags in the recycler are still "common"
