### ISSUE TITLE
Item duplication 

### ISSUE THREAD

**Issue by Flamebom** [Malorolam/LootBags#152]
Putting a crafting station next to a loot bag opener and crafting anything causes an item to go in to the loot bag opener like this.
https://cdn.discordapp.com/attachments/482280661911339012/494678298123698179/Screenshot_160.png
Version: 1.12.2-2.5.7
Forge Version : Twitch?

**Comment by Malorolam** [comment]
That non-lootbag items are ending up in there is likely a Tinker's issue as I've never noticed it occurring with other insertion methods but I'll look into preventing it on my end.

**Comment by Flamebom** [comment]
thanks
