### ISSUE TITLE
More of a question, sorry...

### ISSUE THREAD

**Issue by Shade-Jonezy** [Malorolam/LootBags#153]
In the config in the custom loot portion specifically.  What is the format accepted for NBT Data?  I've been trying to add NBT Data for Immersive Engineering Blueprints and I've had no success.  I've got the NBT through both JEI Integration and Infinity Item Editor.  No matter how I add it I only get the first blueprint and not the others.  They all share the same Meta Data, 0.  {blueprint:"bullet"} is one NBT Tag that is a different blueprint, I think.

**Comment by Malorolam** [comment]
The format is a byte array, you get it with `/lootbags_dumphelditem` while holding it.  If you're doing a lot of these, using `lootbags_dumpinventory` instead will give all items in your inventory in one go.  This will give you a whitelisting entry with default values for minstack, maxstack, and weight you can replace.

**Comment by Shade-Jonezy** [comment]
Is the entire string necessary?  That is a lot of code to paste in the config.

**Comment by Shade-Jonezy** [comment]
[LootBagsInventoryDump.txt](https://github.com/Malorolam/LootBags/files/2457929/LootBagsInventoryDump.txt)

      I still haven't figured out how to get this properly coded into loot bags.  I've put in as is and within brackets.  Although it shows that it the blueprints can be obtained from the loot bags all I get is the same "Electrodes" Blueprint.  I can't figure out where I am going wrong.  May I trouble you as to see where I went wrong.  Here is a sample of how I add them with the brackets:         immersiveengineering:blueprint:0:1:1:20:[31|-117|8|0|0|0|0|0|0|0|-29|98|96|-32|96|-32|76|-54|41|77|45|40|-54|-52|43|97|-32|76|-51|73|77|46|41|-54|79|73|101|0|0|-9|-73|40|-127|27|0|0|0].

**Comment by Malorolam** [comment]
You just copy it as is with no extra characters.  Make sure that the first whitelist entry is on a new line, I noticed with notepad++ it would sometimes show it on a new line but it was actually on the same line as the $STARTWHITELIST command.
Tested this myself and they all work fine, although there's something in the IE code that makes the easter egg blueprint happen, but not reliably.

**Comment by Shade-Jonezy** [comment]
I see so add them without the "[ ]" and use Notepad++ to make sure that I hit enter to place them on different lines?

**Comment by Shade-Jonezy** [comment]
I could use whatever pointers you can give me to make sure this goes well on my end.  Your loot bags mod is awesome by the way.

**Comment by Malorolam** [comment]
Yes, the code parses based off of lines so each new command, including whitelist or blacklist items, must be on it's own line.  Empty lines just add the expected extra read and basic parsing time (insignificant unless your system is extremely old) so don't worry if you put a blank line in by mistake.
The wiki pages on github here go over all the bag config commands and syntax as well as have some tutorials for common changes.

**Comment by Shade-Jonezy** [comment]
From what I can tell they appear to be on new lines.  Would you like me to enclose my loot bag config so you could see where I went wrong?  In the mean time I will try to figure things out.

**Comment by Shade-Jonezy** [comment]
[Loot_Bags_Config_File.zip](https://github.com/Malorolam/LootBags/files/2462892/Loot_Bags_Config_File.zip)

Enclosed in this message is my Config for your Loot Bags Mod.  Maybe you can see where I went wrong because I followed every step and all I get is the Electrodes Blueprint.   If I am to get full benefits I need all five of the blueprints not just the Electrodes Blueprint.

**Comment by Malorolam** [comment]
Everything looks fine to me.

**Comment by Shade-Jonezy** [comment]
Glad to hear everything is set up correctly.  Guess I should try different weights and see if that changes anything.  Thanks for checking the configuration I sent you.  Still a wonderful mod in my opinion.
