### ISSUE TITLE
The Crafting Isn't Working

### ISSUE THREAD

**Issue by MrPolarBear15** [Malorolam/LootBags#158]
I can't craft the next tier of loot bag. Please Help!
[Loot Bag Config.zip](https://github.com/Malorolam/LootBags/files/2464990/Loot.Bag.Config.zip)

**Comment by MrPolarBear15** [comment]
[Loot_Bag Config.txt](https://github.com/Malorolam/LootBags/files/2464999/Loot_Bag.Config.txt)
[lootbag.txt](https://github.com/Malorolam/LootBags/files/2465000/lootbag.txt)

**Comment by Malorolam** [comment]
Lootbag conversion was changed in 1.12 to work through the Bag Storage block.

**Comment by Minecraftdrew2006** [comment]
Maloralam I am playing skyfactory 3 and it does not work

**Comment by Malorolam** [comment]
The latest SF3 version has bag crafting working fine for me.
