### ISSUE TITLE
Blacklists not working?

### ISSUE THREAD

**Issue by zwya** [Malorolam/LootBags#16]
![lootbags](https://cloud.githubusercontent.com/assets/13181070/15572296/ff424876-233f-11e6-94cd-4ea7247588df.jpg)
I am trying to blacklist some items but it's not working at all. I added my own whitelisted items and I removed all chestGenHooks so that the bags are spawning my items only. If it's not too much of a bother, could you help me figure it out?
Lootbags_BagConfig.cfg: http://pastebin.com/wPEMnYLL
Lootbags.cfg: http://pastebin.com/wg5wdWDi
EDIT: I am using version 2.0.6

**Comment by Malorolam** [comment]
Not really sure what's going on, everything looks correct and I can't find any errors in the code.  I'll make an instance later and see if I can duplicate the problem.

**Comment by Malorolam** [comment]
Fixed in Version 2.0.7
