### ISSUE TITLE
Custom Config crashes Dedicated Server

### ISSUE THREAD

**Issue by kreezxil** [Malorolam/LootBags#160]
StoneBlock pack/server uses LootBags and recently when they reconfigured their configs this old bug came up. Perhaps you could put a check in the mod that captures illegally bounded object and disables it.

Server Crash Report: http://paste.ubuntu.com/p/W59P25PhFZ/

Old bug that is similar: https://github.com/Malorolam/LootBags/issues/8

StoneBlock's alternate config that does not work: https://gist.github.com/knoxhack/cff37eec0eccd86a4581b14af1be069f

Crash report thread at StoneBlock in regards to this issue: https://github.com/Sunekaer/stoneBlock/issues/320

**Comment by ShayBox** [comment]
Same as #159

**Comment by Malorolam** [comment]
Same issue, resolution is in #159
