### ISSUE TITLE
Bag Opener recipe is affected by "Disable Recycler" config, rather than "Disable Opener".

### ISSUE THREAD

**Issue by ryankoppenhaver** [Malorolam/LootBags#162]
Setting the "Disable Recycler Recipe" option to false causes both the Recycler and the Opener to be disabled.  (I haven't tested setting "Disable Opener Recipe" to false, but I'm guessing it has no effect.)

https://github.com/Malorolam/LootBags/blob/caafb1b1282c8a2359793842ec4ff46453ae8834/mal/lootbags/recipe/OpenerCondition.java#L20

I think the line above should reference `DISABLEOPENER` instead of `DISABLERECYCLER`.

**Comment by Malorolam** [comment]
Yup, will be fixed in the next version.

**Comment by dwentz89** [comment]
This issue is still happening for me in version 2.5.8.5. "Disable Recycler Recipe" affects both the recycler and the opener, and "Disable Opener Recipe" does nothing.
