### ISSUE TITLE
BagStorage crash :/

### ISSUE THREAD

**Issue by lenase0077** [Malorolam/LootBags#166]
Idk

---- Minecraft Crash Report ----

WARNING: coremods are present:
  ForgelinPlugin (Forgelin-1.8.2.jar)
  SSLoadingPlugin (SereneSeasons-1.12.2-1.2.13-universal.jar)
  OpenModsCorePlugin (OpenModsLib-1.12.2-0.12.1.jar)
Contact their authors BEFORE contacting forge

// Oops.

Time: 12/16/18 9:31 PM
Description: Unexpected error

java.lang.IndexOutOfBoundsException: Index: 0, Size: 0
	at java.util.ArrayList.rangeCheck(Unknown Source)
	at java.util.ArrayList.get(Unknown Source)
	at mal.lootbags.tileentity.TileEntityStorage.<init>(TileEntityStorage.java:40)
	at mal.lootbags.blocks.BlockStorage.func_149915_a(BlockStorage.java:54)
	at net.minecraft.block.Block.createTileEntity(Block.java:1274)
	at net.minecraft.world.chunk.Chunk.func_177422_i(Chunk.java:782)
	at net.minecraft.world.chunk.Chunk.func_177424_a(Chunk.java:800)
	at net.minecraft.world.World.func_175625_s(World.java:2399)
	at com.rwtema.extrautils2.power.ClientPower.clientTick(ClientPower.java:153)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_426_ClientPower_clientTick_ClientTickEvent.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182)
	at net.minecraftforge.fml.common.FMLCommonHandler.onPreClientTick(FMLCommonHandler.java:344)
	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1707)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1097)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:397)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
	at java.util.ArrayList.rangeCheck(Unknown Source)
	at java.util.ArrayList.get(Unknown Source)
	at mal.lootbags.tileentity.TileEntityStorage.<init>(TileEntityStorage.java:40)
	at mal.lootbags.blocks.BlockStorage.func_149915_a(BlockStorage.java:54)
	at net.minecraft.block.Block.createTileEntity(Block.java:1274)
	at net.minecraft.world.chunk.Chunk.func_177422_i(Chunk.java:782)
	at net.minecraft.world.chunk.Chunk.func_177424_a(Chunk.java:800)
	at net.minecraft.world.World.func_175625_s(World.java:2399)
	at com.rwtema.extrautils2.power.ClientPower.clientTick(ClientPower.java:153)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_426_ClientPower_clientTick_ClientTickEvent.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182)
	at net.minecraftforge.fml.common.FMLCommonHandler.onPreClientTick(FMLCommonHandler.java:344)

-- Affected level --
Details:
	Level name: MpServer
	All players: 1 total; [EntityPlayerSP['lenase'/402, l='MpServer', x=19.17, y=63.00, z=109.88]]
	Chunk stats: MultiplayerChunkCache: 309, 309
	Level seed: 0
	Level generator: ID 00 - default, ver 1. Features enabled: false
	Level generator options: 
	Level spawn location: World: (100,64,248), Chunk: (at 4,4,8 in 6,15; contains blocks 96,0,240 to 111,255,255), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Level time: 556103 game time, 503201 day time
	Level dimension: 0
	Level storage version: 0x00000 - Unknown?
	Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
	Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
	Forced entities: 103 total; [EntityPig['Chancho'/263, l='MpServer', x=97.78, y=64.00, z=182.51], EntityBat['Murciélago'/63, l='MpServer', x=-48.56, y=28.06, z=73.67], EntityPig['Chancho'/65, l='MpServer', x=-50.30, y=69.00, z=91.51], EntityCow['Vaca'/66, l='MpServer', x=-51.45, y=67.00, z=100.55], EntityPig['Chancho'/67, l='MpServer', x=-50.52, y=69.00, z=99.84], EntityPig['Chancho'/68, l='MpServer', x=-51.45, y=68.00, z=99.45], EntityCow['Vaca'/69, l='MpServer', x=-52.55, y=66.00, z=100.45], EntityCreeper['Creeper'/70, l='MpServer', x=-48.50, y=64.00, z=107.50], EntityBat['Murciélago'/72, l='MpServer', x=-59.27, y=25.61, z=176.50], EntityCreeper['Creeper'/73, l='MpServer', x=-32.50, y=48.00, z=51.50], EntityZombie['Zombi'/74, l='MpServer', x=-41.77, y=26.00, z=75.50], EntitySpider['Araña'/75, l='MpServer', x=-39.50, y=26.00, z=91.50], EntityBat['Murciélago'/76, l='MpServer', x=-47.42, y=33.00, z=93.67], EntityCow['Vaca'/77, l='MpServer', x=-42.21, y=64.00, z=92.27], Entitydeathdodoo['Deathdodoo'/78, l='MpServer', x=-37.50, y=34.00, z=110.50], EntityPig['Chancho'/79, l='MpServer', x=-44.50, y=67.00, z=105.98], EntityCow['Vaca'/80, l='MpServer', x=-37.99, y=70.00, z=96.64], EntitySquid['Calamar'/81, l='MpServer', x=-42.86, y=62.54, z=121.40], EntityZombie['Zombi'/82, l='MpServer', x=-43.50, y=38.00, z=142.50], EntityZombie['Zombi'/83, l='MpServer', x=-42.50, y=38.00, z=142.50], EntityZombie['Zombi'/84, l='MpServer', x=-40.50, y=38.00, z=144.50], EntityCreeper['Creeper'/92, l='MpServer', x=-29.72, y=17.00, z=60.36], EntityBat['Murciélago'/93, l='MpServer', x=-24.41, y=26.89, z=87.14], EntityBat['Murciélago'/94, l='MpServer', x=-19.74, y=28.15, z=86.23], EntityBat['Murciélago'/95, l='MpServer', x=-23.90, y=26.40, z=82.89], EntityBat['Murciélago'/96, l='MpServer', x=-22.77, y=29.17, z=96.59], EntityCow['Vaca'/97, l='MpServer', x=-27.49, y=79.00, z=159.83], EntityZombie['Zombi'/98, l='MpServer', x=-30.50, y=76.00, z=154.50], EntityCow['Vaca'/99, l='MpServer', x=-21.58, y=80.00, z=153.83], EntityCow['Vaca'/100, l='MpServer', x=-24.80, y=80.00, z=163.47], Entityalter['Alter'/121, l='MpServer', x=-14.50, y=24.00, z=89.50], EntityCreeper['Creeper'/122, l='MpServer', x=-13.51, y=23.00, z=89.55], EntitySkeleton['Esqueleto'/123, l='MpServer', x=-15.69, y=64.00, z=83.50], EntityBat['Murciélago'/124, l='MpServer', x=-3.30, y=20.07, z=110.37], EntityCreeper['Creeper'/125, l='MpServer', x=-5.65, y=89.00, z=164.42], EntityCow['Vaca'/126, l='MpServer', x=-15.56, y=84.00, z=164.23], EntityXPOrb['Orbe de experiencia'/127, l='MpServer', x=7.73, y=62.00, z=110.58], EntityItem['item.item.cloudchunk'/128, l='MpServer', x=7.80, y=62.00, z=110.55], EntityXPOrb['Orbe de experiencia'/129, l='MpServer', x=7.73, y=62.00, z=110.63], EntityItem['item.item.rottenFlesh'/130, l='MpServer', x=7.77, y=62.00, z=110.61], EntityXPOrb['Orbe de experiencia'/131, l='MpServer', x=7.73, y=62.00, z=110.25], EntityXPOrb['Orbe de experiencia'/132, l='MpServer', x=7.73, y=62.00, z=110.37], EntityXPOrb['Orbe de experiencia'/133, l='MpServer', x=7.70, y=62.00, z=110.75], EntityXPOrb['Orbe de experiencia'/134, l='MpServer', x=7.71, y=62.00, z=110.53], EntityXPOrb['Orbe de experiencia'/135, l='MpServer', x=7.73, y=62.00, z=110.63], EntityXPOrb['Orbe de experiencia'/136, l='MpServer', x=7.71, y=62.00, z=110.73], EntityXPOrb['Orbe de experiencia'/137, l='MpServer', x=7.73, y=62.00, z=110.64], EntityItem['item.item.bone'/138, l='MpServer', x=7.77, y=62.00, z=110.30], EntityXPOrb['Orbe de experiencia'/139, l='MpServer', x=7.71, y=62.00, z=110.25], EntityXPOrb['Orbe de experiencia'/140, l='MpServer', x=7.67, y=62.00, z=110.75], EntityXPOrb['Orbe de experiencia'/141, l='MpServer', x=7.54, y=62.00, z=110.75], EntityXPOrb['Orbe de experiencia'/142, l='MpServer', x=7.54, y=62.00, z=110.69], EntityItem['item.item.bow'/143, l='MpServer', x=7.80, y=62.00, z=110.13], EntityItem['item.item.tipped_arrow'/144, l='MpServer', x=7.77, y=62.00, z=110.13], EntityItem['item.item.arrow'/145, l='MpServer', x=7.78, y=62.00, z=110.18], EntityXPOrb['Orbe de experiencia'/146, l='MpServer', x=7.73, y=62.00, z=110.63], EntityPlayerSP['lenase'/402, l='MpServer', x=19.17, y=63.00, z=109.88], EntityZombie['Zombi'/147, l='MpServer', x=4.39, y=89.00, z=164.32], EntityZombie['Zombi'/148, l='MpServer', x=3.92, y=89.00, z=160.90], EntitySkeleton['Esqueleto'/439, l='MpServer', x=-60.30, y=81.00, z=39.30], EntitySkeleton['Esqueleto'/440, l='MpServer', x=-59.21, y=81.00, z=34.47], EntitySkeleton['Esqueleto'/190, l='MpServer', x=29.73, y=56.00, z=97.46], EntityItem['item.item.rottenFlesh'/191, l='MpServer', x=16.14, y=93.00, z=122.42], EntityBat['Murciélago'/448, l='MpServer', x=3.60, y=17.90, z=41.59], EntityCow['Vaca'/193, l='MpServer', x=40.45, y=75.00, z=103.55], EntityCow['Vaca'/449, l='MpServer', x=1.66, y=72.00, z=44.19], EntityZombie['Zombi'/194, l='MpServer', x=32.43, y=67.00, z=110.29], EntityCow['Vaca'/450, l='MpServer', x=4.37, y=72.00, z=43.58], EntityCow['Vaca'/195, l='MpServer', x=47.49, y=110.00, z=138.82], EntityCow['Vaca'/451, l='MpServer', x=6.38, y=71.00, z=37.84], EntityCreeper['Creeper'/196, l='MpServer', x=47.55, y=54.00, z=169.50], EntityCow['Vaca'/452, l='MpServer', x=3.32, y=72.00, z=43.98], EntityCow['Vaca'/197, l='MpServer', x=47.41, y=103.00, z=166.18], EntitySkeleton['Esqueleto'/456, l='MpServer', x=-35.30, y=75.00, z=47.52], EntityCow['Vaca'/203, l='MpServer', x=51.49, y=67.00, z=73.22], EntityCow['Vaca'/204, l='MpServer', x=48.74, y=109.00, z=129.87], EntityBat['Murciélago'/460, l='MpServer', x=-15.20, y=14.45, z=43.92], EntityCow['Vaca'/205, l='MpServer', x=58.20, y=121.00, z=138.51], EntitySkeleton['Esqueleto'/206, l='MpServer', x=58.73, y=68.00, z=159.51], EntityCow['Vaca'/207, l='MpServer', x=53.18, y=102.00, z=157.76], EntityCow['Vaca'/208, l='MpServer', x=51.45, y=104.00, z=167.78], EntityCow['Vaca'/209, l='MpServer', x=49.79, y=104.00, z=169.49], EntityCow['Vaca'/211, l='MpServer', x=52.82, y=105.00, z=180.32], EntityCow['Vaca'/221, l='MpServer', x=64.15, y=64.00, z=65.61], EntityPig['Chancho'/222, l='MpServer', x=75.28, y=123.00, z=143.46], EntityCreeper['Creeper'/223, l='MpServer', x=72.77, y=23.00, z=159.50], EntitySkeleton['Esqueleto'/224, l='MpServer', x=74.27, y=70.00, z=155.49], EntityPig['Chancho'/225, l='MpServer', x=77.50, y=119.00, z=149.50], EntityPig['Chancho'/226, l='MpServer', x=70.67, y=125.00, z=146.50], EntityPig['Chancho'/227, l='MpServer', x=74.51, y=123.00, z=146.64], EntityCreeper['Creeper'/228, l='MpServer', x=69.70, y=20.00, z=160.55], EntityCow['Vaca'/229, l='MpServer', x=65.44, y=96.03, z=172.74], EntityPig['Chancho'/230, l='MpServer', x=77.75, y=75.00, z=181.50], EntitySkeleton['Esqueleto'/231, l='MpServer', x=66.50, y=91.00, z=182.50], EntityCow['Vaca'/244, l='MpServer', x=82.40, y=69.00, z=54.23], EntityCow['Vaca'/245, l='MpServer', x=83.55, y=69.00, z=53.86], EntityCow['Vaca'/246, l='MpServer', x=88.47, y=69.00, z=53.85], EntitySkeleton['Esqueleto'/247, l='MpServer', x=84.50, y=68.00, z=50.50], EntityCow['Vaca'/248, l='MpServer', x=83.46, y=67.00, z=72.16], EntityCow['Vaca'/250, l='MpServer', x=80.15, y=78.00, z=113.48], EntityCow['Vaca'/251, l='MpServer', x=82.97, y=71.00, z=170.46], EntityCow['Vaca'/252, l='MpServer', x=86.79, y=68.00, z=168.52], EntityCow['Vaca'/253, l='MpServer', x=87.99, y=68.00, z=173.66]]
	Retry entities: 0 total; []
	Server brand: fml,forge
	Server type: Integrated singleplayer server
Stacktrace:
	at net.minecraft.client.multiplayer.WorldClient.func_72914_a(WorldClient.java:532)
	at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:2740)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:426)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_151, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 690197872 bytes (658 MB) / 1964470272 bytes (1873 MB) up to 2754871296 bytes (2627 MB)
	JVM Flags: 3 total; -Xmn128M -Xmx2639M -XX:+UseConcMarkSweepGC
	IntCache: cache: 0, tcache: 0, allocated: 12, tallocated: 94
	FML: MCP 9.42 Powered by Forge 14.23.5.2768 Optifine OptiFine_1.12.2_HD_U_E1 61 mods loaded, 61 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State     | ID                       | Version           | Source                                          | Signature                                |
	|:--------- |:------------------------ |:----------------- |:----------------------------------------------- |:---------------------------------------- |
	| UCHIJAAAA | minecraft                | 1.12.2            | minecraft.jar                                   | None                                     |
	| UCHIJAAAA | mcp                      | 9.42              | minecraft.jar                                   | None                                     |
	| UCHIJAAAA | FML                      | 8.0.99.99         | forge-1.12.2-14.23.5.2768.jar                   | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| UCHIJAAAA | forge                    | 14.23.5.2768      | forge-1.12.2-14.23.5.2768.jar                   | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| UCHIJAAAA | openmodscore             | 0.12.1            | minecraft.jar                                   | None                                     |
	| UCHIJAAAA | deconstruction           | 3.0.4             | [MC1.12.2]DeconTable-3.0.4.jar                  | None                                     |
	| UCHIJAAAA | infinitylib              | 1.12.2-1.12.0     | infinitylib-1.12.0.jar                          | None                                     |
	| UCHIJAAAA | agricraft                | 2.12.0-1.12.0-a6  | AgriCraft-2.12.0-1.12.0-a6.jar                  | None                                     |
	| UCHIJAAAA | baubles                  | 1.5.2             | Baubles-1.12-1.5.2.jar                          | None                                     |
	| UCHIJAAAA | bookshelf                | 2.3.567           | Bookshelf-1.12.2-2.3.567.jar                    | d476d1b22b218a10d845928d1665d45fce301b27 |
	| UCHIJAAAA | jei                      | 4.12.1.217        | jei_1.12.2-4.12.1.217.jar                       | None                                     |
	| UCHIJAAAA | botania                  | r1.10-358         | Botania+r1.10-358.jar                           | None                                     |
	| UCHIJAAAA | chesttransporter         | 2.8.8             | ChestTransporter-1.12.2-2.8.8.jar               | None                                     |
	| UCHIJAAAA | cloudboots               | 1.3.2             | CloudBoots-1.12.2-1.3.2.jar                     | None                                     |
	| UCHIJAAAA | codechickenlib           | 3.2.2.353         | CodeChickenLib-1.12.2-3.2.2.353-universal.jar   | f1850c39b2516232a2108a7bd84d1cb5df93b261 |
	| UCHIJAAAA | redstoneflux             | 2.1.0             | RedstoneFlux-1.12-2.1.0.6-universal.jar         | 8a6abf2cb9e141b866580d369ba6548732eff25f |
	| UCHIJAAAA | cofhcore                 | 4.6.1             | CoFHCore-1.12.2-4.6.1.22-universal.jar          | None                                     |
	| UCHIJAAAA | cofhworld                | 1.3.0             | CoFHWorld-1.12.2-1.3.0.6-universal.jar          | 8a6abf2cb9e141b866580d369ba6548732eff25f |
	| UCHIJAAAA | orespawn                 | 3.3.0             | OreSpawn-1.12-3.3.0.155.jar                     | d476d1b22b218a10d845928d1665d45fce301b27 |
	| UCHIJAAAA | densemetals              | 1.2.0             | DenseMetals-1.12-1.2.0.20.jar                   | d476d1b22b218a10d845928d1665d45fce301b27 |
	| UCHIJAAAA | eplus                    | 5.0.174           | EnchantingPlus-1.12.2-5.0.174.jar               | d476d1b22b218a10d845928d1665d45fce301b27 |
	| UCHIJAAAA | endercrop                | 1.12.2-1.6.0      | endercrop-1.12.2-1.6.0.jar                      | None                                     |
	| UCHIJAAAA | extrautils2              | 1.0               | extrautils2-1.12-1.9.8.jar                      | None                                     |
	| UCHIJAAAA | forgelin                 | 1.8.2             | Forgelin-1.8.2.jar                              | None                                     |
	| UCHIJAAAA | cfm                      | 5.17.0            | furniture-5.17.0-1.12.2.jar                     | None                                     |
	| UCHIJAAAA | gokistats                | @version@         | gokiStats-1.2.5.1.jar                           | None                                     |
	| UCHIJAAAA | ic2                      | 2.8.73-ex112      | industrialcraft-2-2.8.73-ex112.jar              | de041f9f6187debbc77034a344134053277aa3b0 |
	| UCHIJAAAA | teslacorelib             | 1.0.15            | tesla-core-lib-1.12.2-1.0.15.jar                | d476d1b22b218a10d845928d1665d45fce301b27 |
	| UCHIJAAAA | industrialforegoing      | 1.12.2-1.12.2     | industrialforegoing-1.12.2-1.11.10-223.jar      | None                                     |
	| UCHIJAAAA | ionitems                 | 1.1.2             | IonItems-1.1.2.jar                              | None                                     |
	| UCHIJAAAA | ironbackpacks            | 1.12.2-3.0.8-12   | IronBackpacks-1.12.2-3.0.8-12.jar               | None                                     |
	| UCHIJAAAA | ironchest                | 1.12.2-7.0.52.837 | ironchest-1.12.2-7.0.52.837.jar                 | None                                     |
	| UCHIJAAAA | journeymap               | 1.12.2-5.5.2      | journeymap-1.12.2-5.5.2.jar                     | None                                     |
	| UCHIJAAAA | lockyzextradimensionsmod | V.2.4.0 Part 1    | LEDM+V.2.4.0+Part+One.jar                       | None                                     |
	| UCHIJAAAA | lootbags                 | 2.5.7             | LootBags-1.12.2-2.5.7.jar                       | None                                     |
	| UCHIJAAAA | lostquiver               | 1.0 - MC 1.12.2   | lostquiver-1.0.jar                              | None                                     |
	| UCHIJAAAA | mousetweaks              | 2.9               | MouseTweaks-2.9-mc1.12.2.jar                    | None                                     |
	| UCHIJAAAA | obsidiantools            | 1.8.2             | ObsidianTools-1.8.2.jar                         | None                                     |
	| UCHIJAAAA | openmods                 | 0.12.1            | OpenModsLib-1.12.2-0.12.1.jar                   | d2a9a8e8440196e26a268d1f3ddc01b2e9c572a5 |
	| UCHIJAAAA | openblocks               | 1.8               | OpenBlocks-1.12.2-1.8.jar                       | d2a9a8e8440196e26a268d1f3ddc01b2e9c572a5 |
	| UCHIJAAAA | potioncore               | 1.6_for_1.12.2    | PotionCore-1.6_for_1.12.2.jar                   | None                                     |
	| UCHIJAAAA | qualitytools             | 1.0.6_for_1.12.2  | QualityTools-1.0.6_for_1.12.2.jar               | None                                     |
	| UCHIJAAAA | roguelike                | 1.8.0             | RoguelikeDungeons-1.12.2-1.8.0.jar              | None                                     |
	| UCHIJAAAA | roughmobs                | 2.0.0             | roughmobs2-1.12.2_2.0.11.jar                    | None                                     |
	| UCHIJAAAA | sereneseasons            | 1.2.13            | SereneSeasons-1.12.2-1.2.13-universal.jar       | None                                     |
	| UCHIJAAAA | sparkshammers            | @VERSION@         | sparkshammers-1.12.2-1.9.2.jar                  | None                                     |
	| UCHIJAAAA | spectrite                | 1.6.7             | spectrite-1.6.7.jar                             | 00119cfc089819bbcd2f9166a50c7f3df88ded78 |
	| UCHIJAAAA | thermalfoundation        | 2.6.1             | ThermalFoundation-1.12.2-2.6.1.22-universal.jar | 8a6abf2cb9e141b866580d369ba6548732eff25f |
	| UCHIJAAAA | thermalexpansion         | 5.5.2             | ThermalExpansion-1.12.2-5.5.2.39-universal.jar  | 8a6abf2cb9e141b866580d369ba6548732eff25f |
	| UCHIJAAAA | thermalcultivation       | 0.3.1             | ThermalCultivation-1.12.2-0.3.1.8-universal.jar | 8a6abf2cb9e141b866580d369ba6548732eff25f |
	| UCHIJAAAA | thermaldynamics          | 2.5.3             | ThermalDynamics-1.12.2-2.5.3.16-universal.jar   | 8a6abf2cb9e141b866580d369ba6548732eff25f |
	| UCHIJAAAA | tombstone                | 3.3.0             | tombstone-3.3.0-1.12.jar                        | None                                     |
	| UCHIJAAAA | torchmaster              | 1.6.4.62          | torchmaster_1.12.2-1.6.4.62.jar                 | 5e9a436b366831c8f54a7e80b015784da69278c6 |
	| UCHIJAAAA | treechopper              | 1.2.4             | TreeChopper-1.12.2-1.2.4.jar                    | None                                     |
	| UCHIJAAAA | uteamcore                | 2.0.0.82          | u_team_core-1.12.2-2.0.0.82.jar                 | None                                     |
	| UCHIJAAAA | wanionlib                | 1.12.2-2.0        | WanionLib-1.12.2-2.0.jar                        | None                                     |
	| UCHIJAAAA | waystones                | 4.0.67            | Waystones_1.12.2-4.0.67.jar                     | None                                     |
	| UCHIJAAAA | valoegheses_be           | 1.0 Alpha 3       | Zoesteria+Public+Alpha+1.2.1.jar                | None                                     |
	| UCHIJAAAA | vt                       | 1.4               | VanillaTweaks-1.4.jar                           | None                                     |
	| UCHIJAAAA | teslacorelib_registries  | 1.0.15            | tesla-core-lib-1.12.2-1.0.15.jar                | None                                     |
	| UCHIJAAAA | unidict                  | 1.12.2-2.9.1      | UniDict-1.12.2-2.9.1.jar                        | None                                     |

	Loaded coremods (and transformers): 
ForgelinPlugin (Forgelin-1.8.2.jar)
  
SSLoadingPlugin (SereneSeasons-1.12.2-1.2.13-universal.jar)
  sereneseasons.asm.transformer.EntityRendererTransformer
  sereneseasons.asm.transformer.WorldTransformer
OpenModsCorePlugin (OpenModsLib-1.12.2-0.12.1.jar)
  openmods.core.OpenModsClassTransformer
	GL info: ' Vendor: 'ATI Technologies Inc.' Version: '4.6.13543 Compatibility Profile Context 25.20.15002.58' Renderer: 'AMD Radeon R7 200 Series'
	OpenModsLib class transformers: [llama_null_fix:FINISHED],[horse_base_null_fix:FINISHED],[pre_world_render_hook:FINISHED],[player_render_hook:FINISHED],[horse_null_fix:FINISHED]
	Launched Version: ForgeOptiFine 1.12.2
	LWJGL: 2.9.4
	OpenGL: AMD Radeon R7 200 Series GL version 4.6.13543 Compatibility Profile Context 25.20.15002.58, ATI Technologies Inc.
	GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Packs: 
	Current Language: Español (Argentina)
	Profiler Position: N/A (disabled)
	CPU: 4x Intel(R) Core(TM) i5-7400 CPU @ 3.00GHz
	OptiFine Version: OptiFine_1.12.2_HD_U_E1
	OptiFine Build: 20180628-111228
	Render Distance Chunks: 12
	Mipmaps: 0
	Anisotropic Filtering: 1
	Antialiasing: 0
	Multitexture: false
	Shaders: null
	OpenGlVersion: 4.6.13543 Compatibility Profile Context 25.20.15002.58
	OpenGlRenderer: AMD Radeon R7 200 Series
	OpenGlVendor: ATI Technologies Inc.
	CpuCount: 4

**Comment by Malorolam** [comment]
If you've tweaked the lootbag config files at all, post them here, if you haven't delete them and run the game again.

**Comment by lenase0077** [comment]
Thanks n-n
