### ISSUE TITLE
fixed: bags vanish when thrown on ground?

### ISSUE THREAD

**Issue by Dorkintentions** [Malorolam/LootBags#167]
Edit: deleted the config files then re-loaded the game and it seems to be running smoothly

They appear for a fraction of a second and then immediately disappear, even when dropped from mobs. I've tried changing to a different version of the mod but that didn't help at all.

**Comment by Malorolam** [comment]
Yup, the bags have code to destroy them if they're empty and that includes bags that don't have any items possible to drop.
