### ISSUE TITLE
Crash 2.0.7

### ISSUE THREAD

**Issue by SvEgiiVEteR** [Malorolam/LootBags#17]
https://gist.github.com/0194831ed0f4db6bc6f078b22b682461
or
https://gist.github.com/d87291139c4a9fd4e13060c64cfb4a10
or
https://gist.github.com/1be11d9ce226bd906ceba9f5b29b2b48

2.0.6 works

**Comment by Malorolam** [comment]
Hmm... nothing should be accessing the array it's complaining about.

Take out NEILootbags and see if it still happens, that seems the most likely culprit. If that doesn't do it, then one of the lag and loading fix mods you have might be doing something naughty.

**Comment by SvEgiiVEteR** [comment]
@Malorolam 
https://gist.github.com/0651abe199eaee6beb57647520fd5c6e

**Comment by Malorolam** [comment]
I found the problem, in short you have a malformed blacklist entry somewhere, so the code is failing to find the item after the refresh, and it's removing the item from the same list it's reading, causing the error.  2.0.8 should fix it, and once it stops crashing you should be able to see clearly in the log what item isn't blacklisted correctly and fix it in the config.

**Comment by SvEgiiVEteR** [comment]
strange. I removed configs ..
check out the new version thanks)
