### ISSUE TITLE
Too many bags

### ISSUE THREAD

**Issue by logitechQ** [Malorolam/LootBags#172]
How do I config so less bags spawn? say 10% of default.

**Comment by Malorolam** [comment]
Bag drop chances work off an x/y ratio. For bag drop rates, there's two config entries that apply to it. In lootbags.cfg, there is I:"1 Weighting Resolution"=, which is the y and in Lootbags_BagConfig.cfg for each bag there are $PASSIVESPAWNWEIGHT, $PLAYERSPAWNWEIGHT, $MOBSPAWNWEIGHT, and $BOSSSPAWNWEIGHT, which is the x depending on the situation. The wiki here goes into more detail about what each one applies to.
The easiest way to make all bags rarer (or more common) across the board is to increase (or decrease) the weighting resolution by some multiple.

**Comment by logitechQ** [comment]
Thank you :) I figured it out now
