### ISSUE TITLE
[Maybe a bug] I was adding some items to the Recycler list. 

### ISSUE THREAD

**Issue by Juanchio88** [Malorolam/LootBags#179]
Hi there, I love this mod. 

Ok down to what i think is a bug. I was adding some Actually Additions to the recycler whitelist.

The items are the Crystals and their blocks, both empowered and normal.

My config looks like this. 

https://pastebin.com/zKkHwX6q

After setting it up, i ran the /lootbag_reloadconfig, and some items where acepted by the recycler. However after doing the same command again, the recycler no longer takes the items it already took, but instead took some other ones.

Apparently, its taking the items at random. To me it looks like a bug, however i dont have enough knowledge to know for sure. 

If its not a bug can you guide me on what am I doing wrong?

BTW I forgot. Im using Minecraft 1.12 
LootBag Ver 2.5.8.5
Minecraft forge 12.23.5.2815

**Comment by Malorolam** [comment]
Hmm, do the changes apply correctly when you restart the game?

**Comment by Juanchio88** [comment]
Nope after restarting the game, it behaves the same. Diferent items at random. And even when doing the /reloadconfig, the same happens. Diferent items at random everytime.

**Comment by Malorolam** [comment]
Your whitelist entries are incorrect, `actuallyadditions:item_crystal:0:1:64:20` is for whitelisting in a bag, the recycler only needs the item data and weight. I don't know why you're getting different items.

**Comment by Juanchio88** [comment]
I did what the tutorial said:

Whitelist an item to be recyclable.  The entry must be in the form <modid >:< itemname>:< damage>:<weighting >:[<nbt data (seriously don't try to make this by hand)> (optional)]  

 xD Plus in the recycler description is ask for more values than just Item Data and weight. I did obtain the data by doing a /lootbag_inventorydumb.


Sorry to bother, but how should be the correct spelling for those items then? And further more, how do i obtain those.

**Comment by Malorolam** [comment]
Yes, the inventory dump command is assuming you're going to whitelist the item in the bag, so it gives all needed information. Each of the black and white lists in lootbags.cfg state in their description what they need.

The inventory dump command gives `<mod id>:<item name>:<metadata>:<min stack (1 almost always)>:<max stack for that item>:<sample weight of 20>:<nbt data if it has it>`

**Comment by Juanchio88** [comment]
Ok thats a lot more easier than i originally understood haha. So pretty much my values should look like this 

        actuallyadditions:block_crystal:0:64
        actuallyadditions:block_crystal:1:64
        actuallyadditions:block_crystal:2:64
        actuallyadditions:block_crystal:3:64
        actuallyadditions:block_crystal:4:64
        actuallyadditions:block_crystal:5:64

Right?

**Comment by Malorolam** [comment]
Yup, that's right. Keep in mind the weight is 64 for the recycler calculation, so you might want to adjust it to get the value you want per item in the recycler.

**Comment by Juanchio88** [comment]
Thanks so much Malorolam! And sorry for the false positive. Ill give it a shot and if the thread is unlocked update so anyone in the future can see the info and result.

**Comment by Juanchio88** [comment]
UPDATE (Problem Solved) What Malorolam stated was 100% correct. Did as he suggested and worked perfectly. Just use Item ID and weight.
