### ISSUE TITLE
[suggestion]make lootbag configs accept entire loot tables

### ISSUE THREAD

**Issue by Jackiecrazy** [Malorolam/LootBags#181]
I'm making loot bags for Betweenlands, and I'd like them to essentially be pots of chance. Is there a way to directly use the loot table of the pots of chance, ad verbatim, and apply them only to that specific bag?

**Comment by Jackiecrazy** [comment]
Addendum: how would I configure it if I want specific types of loot bags to drop from specific monsters? Do I add all their names to $INTERNALNAMES, or should I just disable its spawn and use a mob loot tweaker to individually add the drops?

**Comment by Malorolam** [comment]
Yes, you can put the pots of chance loot table into a bag's whitelist, you just have to find out it's internal name, `/lootbags_identifysources` will generate a list of all loot sources that instance knows about, you just have to find the right one (probably potofchance or something like that)

You would have to add the names via the bag config, yes. You can use an external utility for this too, but keep in mind I don't drop items through the same system as everything else so you'd want to make sure you disable drops from lootbags itself.

**Comment by Jackiecrazy** [comment]
So, after getting the loot table (loottweaker, I thank thee), do I have to manually add each entry to the bag config again, or could I just put the name of the loot table into the bag's whitelist and call it a day? If it's that easy I'll probably make loot bags for all the other dimensions, too, and it would be ideal to supplement a grindy mod like AoA. Dropping all mob drops from a dimension as chance drops from a dimension-specific loot bag would add some thematic consistency and cut down on repetition.

**Comment by Malorolam** [comment]
You just put the name in the bag's whitelist.

**Comment by Jackiecrazy** [comment]
hmm, it's not working for me. I put the following in the bag config:
$STARTWHITELIST
        thebetweenlands:loot/common_chest_loot
thebetweenlands:loot/common_pot_loot
thebetweenlands:loot/dungeon_pot_loot
thebetweenlands:entities/frog
thebetweenlands:entities/dragonfly
thebetweenlands:entities/angler
thebetweenlands:entities/blood_snail
thebetweenlands:entities/chiromaw
thebetweenlands:entities/leech
thebetweenlands:entities/lurker
thebetweenlands:entities/mire_snail
thebetweenlands:entities/pyrad
thebetweenlands:entities/root_sprite
thebetweenlands:entities/silt_crab
thebetweenlands:entities/sludge
thebetweenlands:entities/sporeling
thebetweenlands:entities/swamp_hag
thebetweenlands:entities/wight
    $ENDWHITELIST
And in game it tells me that "bag disabled - loot table is empty. This is not good".
What did I do wrong?

**Comment by Malorolam** [comment]
Something broke internally, that should be correct.

**Comment by Jackiecrazy** [comment]
Something broke internally? How should I fix that on my end? I am quite sure that the loot tables actually exist.

**Comment by Jackiecrazy** [comment]
For reference this is the entire file:

$STARTBAG:lootbag_Swamped:5
    $BAGCOLOR:148|178|28:0|100|0
    $ISSECRET:false
    $BAGTEXTCOLOR:$DARK_GREEN
    $BAGTEXTUNOPENED:$DARK_GREEN:Made of some sturdy fabric.
    $BAGTEXTOPENED:$DARK_GREEN:It disintegrates in front of your eyes.
    $BAGTEXTSHIFT:$DARK_GREEN:An artifact of the past?
    $BAGVALUE:16:-1
    $PASSIVESPAWNWEIGHT:25
    $PLAYERSPAWNWEIGHT:25
    $MOBSPAWNWEIGHT:25
    $BOSSSPAWNWEIGHT:25
    $USEGENERALLOOTSOURCES:false
    $MAXIMUMITEMS:5
    $MINIMUMITEMS:1
    $PREVENTITEMREPEATS:item
    $EXCLUDEENTITIES:true
    $STARTENTITYLIST
    $ENDENTITYLIST
    $STARTWHITELIST
        thebetweenlands:loot/common_chest_loot
thebetweenlands:loot/common_pot_loot
thebetweenlands:loot/dungeon_pot_loot
thebetweenlands:entities/frog
thebetweenlands:entities/dragonfly
thebetweenlands:entities/angler
thebetweenlands:entities/blood_snail
thebetweenlands:entities/chiromaw
thebetweenlands:entities/leech
thebetweenlands:entities/lurker
thebetweenlands:entities/mire_snail
thebetweenlands:entities/pyrad
thebetweenlands:entities/root_sprite
thebetweenlands:entities/silt_crab
thebetweenlands:entities/sludge
thebetweenlands:entities/sporeling
thebetweenlands:entities/swamp_hag
thebetweenlands:entities/wight
    $ENDWHITELIST
$STARTBLACKLIST
lootbags:itemlootbag:0
$ENDBLACKLIST
$ENDBAG:lootbag_Swamped

**Comment by Jackiecrazy** [comment]
oh... turns out I just had to delete a new line that I put between the bags for organization o.o
Thanks! Gotta tweak with loot weight to make sure stuff's balanced now...

**Comment by Malorolam** [comment]
There's some issue that's causing the betweenlands entries to break, but vanilla ones to work fine with an otherwise identical config.

**Comment by Jackiecrazy** [comment]
I found the solution. I had a line break before the entry which messed everything up (thank you log file), thanks!
