### ISSUE TITLE
Not an issue, a question

### ISSUE THREAD

**Issue by Ashakiwi** [Malorolam/LootBags#19]
Hi! I'm attempting to figure out how to make a bag only pull from the whitelist. Is this possible? D: 

Have a great day!
Ashakiwi

**Comment by Malorolam** [comment]
If you mean have a bag only give items from a whitelist, then yes.  Simply set $USEGENERALLOOTSOURCES to false and whitelist the items you want dropped.  For examples of how to do it in the bag config, take a look at the secret bags.

**Comment by Ashakiwi** [comment]
I figured it out right after I posted the question. *feels silly*
