### ISSUE TITLE
Loot Bag Duplication Bug

### ISSUE THREAD

**Issue by Darkosto** [Malorolam/LootBags#20]
Hello,

While testing, I've discovered the loot bags can be duplicated. The way to make this happen is: 

1. Open a loot bag GUI
2. Have a machine/block pull the loot bag from your inventory

You'll be able to pull the items from the loot bag and a copy of that exact loot bag has been duplicated by the machine you had pull from your inventory. This is not the fault of the machine, such as Steve's Factory Manager, but loot bags not checking whether or not the bag is still in the player inventory when the GUI is open. Botania, Extra Utils, and a number of other mods simply close the GUI and transfer the bag when moved by the factory block.

Thanks!

**Comment by Malorolam** [comment]
I just fixed this in 2.0.11, it now a) updates the itemstack whenever a slot is clicked, and b) verifies the itemstack is still in the slot before allowing to interact with a slot.
