### ISSUE TITLE
Game crashes upon killing mobs

### ISSUE THREAD

**Issue by Raithion** [Malorolam/LootBags#201]
Hello, I'm having an issue where my game crashes occasionally when mobs die. This includes both passive and hostile mobs, and happens randomly upon them dying in any way, whether it be natural causes (skeletons burning in daylight) or by player kills. Any help would be much appreciated.

My most recent crash log:
https://pastebin.com/dhgXYdze

My custom bag config file:
https://pastebin.com/8UfkJN9V (Item drop sections are still unfinished, but it doesn't matter.)

**Comment by Malorolam** [comment]
None of your bags are capable of dropping. As long as you have any bag that can drop from each category it shouldn't crash any more.
    $PASSIVESPAWNWEIGHT:0
    $PLAYERSPAWNWEIGHT:0
    $MOBSPAWNWEIGHT:0
    $BOSSSPAWNWEIGHT:0

**Comment by Raithion** [comment]
> None of your bags are capable of dropping. As long as you have any bag that can drop from each category it shouldn't crash any more.
> $PASSIVESPAWNWEIGHT:0
> $PLAYERSPAWNWEIGHT:0
> $MOBSPAWNWEIGHT:0
> $BOSSSPAWNWEIGHT:0

Thanks for the reply! It may sound odd, but I was actually looking to make my loot bags craft-only, and not have them drop from any mobs, hence the 0's. I have a system in mind in which bosses drop materials used to craft the loot bags, making them guaranteed to be obtainable after a few boss kills. Is having 0% drop rates possible, or do I have to give them a chance to drop from mobs?

**Comment by Malorolam** [comment]
It's likely an oversight on my part that's easy to fix, but because of time issues I can't really say if I will get another update out anytime soon. As long as you have one bag that can drop from each of those categories it shouldn't crash, so you can keep the crafted bags the same and just make one that can rarely show up.

**Comment by Raithion** [comment]
Alright, I'll try that. Thanks!
