### ISSUE TITLE
Crash with lootbags+loottweaker 1.12

### ISSUE THREAD

**Issue by Saereth** [Malorolam/LootBags#203]
Getting a crash with loottweaker and lootbags installed. If I disable either mod the crashes stop. 
here is the crashlog:
https://gist.github.com/Saereth/ca12058657a9b8379f91d25d7cc39470

and config files:
Lootbags_BagConfig.cfg
https://gist.github.com/Saereth/7598f8bc2257a381000563cb8c669f68

lootbags.cfg
https://gist.github.com/Saereth/11db805dd4ad30ec8434c545e1df41a3

Happy to provide any other info, let me know if you have a fix/work around, thanks!

**Comment by Daomephsta** [comment]
This is wholly on LootTweaker's side, this issue can be closed.
