### ISSUE TITLE
Loot Bag Desync

### ISSUE THREAD

**Issue by Darkosto** [Malorolam/LootBags#22]
There seems to be a desync when using the loot bag on many occasion in single or multiplayer. When you remove all items from the bags, the bag remains until the inventory is updated:

https://sx.artdude.uk/hotlink-ok/darkosto/kFsj-51a30-1472188096.mp4

This happens with all bags of any type. 

Is there a possibility of removing the issue?

Thanks!
Darkosto

**Comment by Malorolam** [comment]
It should be fixed in 2.0.14.
