### ISSUE TITLE
OpenComputers Support

### ISSUE THREAD

**Issue by spannerman79** [Malorolam/LootBags#23]
Lootbag: [v2.0.15](https://minecraft.curseforge.com/projects/lootbags/files/2326437)
OpenComputers: [1.6.0.7-rc.1](https://minecraft.curseforge.com/projects/opencomputers/files/2320098)

It seems that Lootbags has issues with correctly generating loot from OpenComputers.  Not once has lootbags been able to generate a disk that isn't a standard disk.

When I did a `/lootbags_pullnbt` this is what was in the dump file;
`OpenComputers:item:4:1:64:20:31|-117|8|0|0|0|0|0|0|0|45|-115|-79|10|-62|64|16|68|7|21|61|18|-80|-78|-79|75|-87|-115|31|-112|86|72|105|-118|124|-63|122|57|37|-80|-105|61|-18|-42|-30|-2|-34|21|-84|-26|49|-68|97|26|-96|-63|65|124|63|-109|-110|67|107|-12|42|55|-90|103|96|-20|37|-123|85|10|-74|112|86|123|97|-55|0|54|-26|-49|75|73|76|-43|97|-9|-96|24|112|30|77|28|-89|-18|98|-103|73|-105|-11|-35|77|-75|104|-120|87|56|28|109|-53|34|58|-112|87|-55|21|-89|-97|124|-105|-104|62|26|114|-23|-1|31|95|44|18|-82|108|-120|0|0|0`

Using Minetweakers `/mt hand` shows the following:
`<OpenComputers:item:4>.withTag({"oc:data": {"oc:fs.label": "openos"}, "oc:color": 2, display: {Name: "OpenOS (Operating System)"}, "oc:lootFactory": "OpenComputers:openos"})`

It seems Lootbags has issues with generating the extra NBT data.

This is an excerpt from the OpenComputers config file that I think that should also be of note:
```
    # The probability (or rather, weighted chance) that a program disk is
    # spawned as loot in a treasure chest. For reference, iron ingots have
    # a value of 10, gold ingots a value of 5 and and diamonds a value of 3.
    # This is the chance *that* a disk is created. Which disk that will be
    # is decided in an extra roll of the dice.
    lootProbability=5
```

**Comment by Malorolam** [comment]
What is the problem?  I made a test instance where the only item the bag could give is exactly what you put and I got the OpenOS disk every time.
