### ISSUE TITLE
INFO spam EntitySpirit

### ISSUE THREAD

**Issue by C0rn3j** [Malorolam/LootBags#27]
http://pastebin.com/xVQwk90E

Forge 2092

LootBags-1.10.2-2.1.1.jar

Was in the Nether when it happened, might be Spirit added by Quark, or perhaps EvilCraft

**Comment by Malorolam** [comment]
That entity is not a child of EntityMob, EntityAnimal, or EntityPlayer, nor does it implement IMob or IAnimals, it's not a problem, that's just an info message.  I'll have a config option to disable the various info messages in the next version.

**Comment by C0rn3j** [comment]
Could these info messages be disabled by default?

http://pastebin.com/y6sRJ2NS

Or at the very least reduce them to a single line instead of repeating the line 8-10 times.

Unless the mod author for the entity should deal with the entity differently so this doesn't happen?

**Comment by Malorolam** [comment]
Many of the info messages are important for diagnosing issues, both for errors in the mod as well as setting up custom bag setups, so I'm not inclined to disable them by default, I feel it will simply increase the number of issue requests I get and the amount of back and forth I need to do to solve issues.
The mod causing the messages should be using the interfaces IMob and IAnimal to indicate if the entity is an enemy or passive mob, not doing so would cause issues with other mods that interact with modded mobs, mine is just more verbose about the issue.

**Comment by C0rn3j** [comment]
Alright, I'll just report it to mods causing the INFO to pop up then, thanks.
