### ISSUE TITLE
Common Lootbags issue

### ISSUE THREAD

**Issue by MarioLuigi55** [Malorolam/LootBags#28]
Common lootbags just disappear after opening them, they do not give any items. Every other Lootbag works. I am using MC 1.10.2

**Comment by Malorolam** [comment]
I need a mod list, log file, and if you've changed it, the config file to be able to help.  Also, there was an issue fixed yesterday involving Enchanting Plus that caused this same problem, so make sure you're on the latest version.

**Comment by MarioLuigi55** [comment]
[config of lootbags.txt](https://github.com/Malorolam/LootBags/files/491133/config.of.lootbags.txt)

Log (there are all mods listed in it) :  [2016-09-24-7.log.txt](https://github.com/Malorolam/LootBags/files/491136/2016-09-24-7.log.txt)

**Comment by Malorolam** [comment]
I need the log called fml-client-latest.log

**Comment by MarioLuigi55** [comment]
[fml-client-latest.log.txt](https://github.com/Malorolam/LootBags/files/491155/fml-client-latest.log.txt)

**Comment by Malorolam** [comment]
Everything looks fine in the log, the common bag has a weight and I don't see any errors with the tables.

**Comment by MarioLuigi55** [comment]
OK, it is fine now. I just reinstalled the mod

**Comment by MarioLuigi55** [comment]
Wait... Is the worn out bag supposed to be useless?

**Comment by Malorolam** [comment]
For the most part, yes.  It just gives you a bed, which once you have one more don't help more.  It's a joke about a bunch of issue reports I got early on in the development cycle for Sky Factory 2 about people mistaking the Magical Crops holiday boxes for my bags.  It used to give a cake, but I changed it in 2.1.0.
