### ISSUE TITLE
1.10.2 Crash

### ISSUE THREAD

**Issue by Darkosto** [Malorolam/LootBags#29]
Hey Mal,

I just got this crash:
http://pastebin.com/f6qMCFpT

I'm not sure if this is related, but the game seems to throw a fit when you right click a loot bag into a storage drawer, too. Your armor and items are all randomized in your inventory and a restart of the world is required to get it back to normal.

Forge: 2094
Loot Bags: 2.1.2

**Comment by Darkosto** [comment]
And now it's crashing the world out on load so I can't get back in without removing the mod.

**Comment by Malorolam** [comment]
Yeah, I missed a null item check so the bag opener is stuck trying to process a null item.  The other problem appears to be both my bag opening container code and the storage drawers store item code is running, but not the gui code somehow.

**Comment by Malorolam** [comment]
Both issues should be fixed in 2.1.3

**Comment by Darkosto** [comment]
Thank you! All fixed up!
