### ISSUE TITLE
Crash using bag opener - Minecraft 1.10.2  LootBags 2.1.3

### ISSUE THREAD

**Issue by YaibaToKen** [Malorolam/LootBags#30]
Just like the title says, as soon as I popped a wornout bag into a bag opener, the world crashed. World crashes on load afterwards.

Here are the crash logs:
[crash-2016-09-30_10.40.34-server.txt](https://github.com/Malorolam/LootBags/files/502604/crash-2016-09-30_10.40.34-server.txt)
[crash-2016-09-30_10.42.11-server.txt](https://github.com/Malorolam/LootBags/files/502605/crash-2016-09-30_10.42.11-server.txt)

**Comment by Malorolam** [comment]
This was fixed in 2.1.3.

**Comment by YaibaToKen** [comment]
Apologies, on a second look through my mod folder I noticed i had not replaced the mod with the new version :'( sorry
