### ISSUE TITLE
Issue with EZStorage 2 and Loot Bags

### ISSUE THREAD

**Issue by DatrixTHLK** [Malorolam/LootBags#33]
Hi Malorolam,
This an issue I've been having and thought I'd keep you updated with it
https://github.com/zerofall/EZStorage2/issues/42

**Comment by Malorolam** [comment]
I gave the issue a quick whirl with just EZStorage and Lootbags and I couldn't duplicate the bug from the steps you gave in the other issue.  If you can give me more precise instructions on exactly how you cause the issue with my bags, starting from loading the game, including what items are in your inventory then I might be able to help more.  Just from what you posted, it sounds like something is causing a desync, so the item isn't the same on both client and server and not opening the gui.

**Comment by DatrixTHLK** [comment]
It's a bit complicated... When I first enter minecraft the loot bags I have drop the items they hold in them. Once I go into the EZStorage 2 inventory and move the loot bags to my main hand slots, then quit out of the inventory GUI, right-click the bag nothing drops out of it. I do this multiple times and not a thing drops out of it. What usually happens is that restarting minecraft seems to work again until the issue resurfaces again.

**Comment by DatrixTHLK** [comment]
Of course when I look into my personal inventory then items have resuffeld back to their original spots before I moved them around.

**Comment by DatrixTHLK** [comment]
It was the [telepads](https://minecraft.curseforge.com/projects/telepad) mod all along causing the desync issue.
