### ISSUE TITLE
Lootbags GUI doesn't close after emptying anymore

### ISSUE THREAD

**Issue by C0rn3j** [Malorolam/LootBags#34]
http://i.imgur.com/LodcAs6.png

This window used to close instead of staying on the screen, allowing for fast lootbags opening. Now it just pointlessly stays open.

Modlist: http://pastebin.com/z6fbQb3Y

Forge: 2114

**Comment by Malorolam** [comment]
I cannot duplicate this issue in 2117.

**Comment by C0rn3j** [comment]
Nope, still happens in 2118.
I don't want to troubleshoot it right now, so here is my modpack if you want to.

https://www.dropbox.com/sh/g4ig35lzo53zgv1/AADd8iGv5PujFc1dSrpOBGd0a?dl=1

**Comment by Malorolam** [comment]
It's because of AdvancedRocketry, something they're doing is interfering with calling net.minecraft.inventory.Container.canInteractWith(EntityPlayer playerIn)

**Comment by Malorolam** [comment]
The issue on AdvancedRocketry has been closed, so everything should work properly once that update is released.

**Comment by C0rn3j** [comment]
Thanks a lot for going through the trouble!
