### ISSUE TITLE
question regarding config(mc 1.10.2)

### ISSUE THREAD

**Issue by SDUBZ** [Malorolam/LootBags#39]
drop chances" {
    # This is the resolution of the bag drop chances.  Only change this if you want bags with rarity resolutions > 0.1%
    I:"1 Weighting Resolution"=100

why was the config set to 1000 by default and what is 1000 in percentage chance?

**Comment by Malorolam** [comment]
The chance to get a bag is expressed as a ratio of weight/resolution, so 15/100 is a 15% chance to drop, but 15/1000 is a 1.5% chance to drop.

**Comment by SDUBZ** [comment]
also noticed something wierd is happening with loot bags and everlasting abilities when you get a ability totem in a loot bag it always says none on it for some reason

**Comment by Malorolam** [comment]
I don't know what ability totems are or what mod adds them, but it sounds like they're using NBT data to express their effect and that's not being carried over.

**Comment by SDUBZ** [comment]
yeah its very odd

**Comment by SDUBZ** [comment]
well i was just wondering if it would be possible to get some sort of compat between your mod and everlasting abilities or if there was a way to register the items manually in some way?
also heres the mod page https://minecraft.curseforge.com/projects/everlastingabilities?gameCategorySlug=mc-mods&projectID=248353 if you were interested in getting these 2 mods to work together

**Comment by Malorolam** [comment]
As far as I can tell, everything is working perfectly on my end, the loot function is being applied and NBT data is being added to the item that's spawned.  
You can whitelist them manually with the NBT data applied through the lootbags_pullNBT command.
