### ISSUE TITLE
NPE Error

### ISSUE THREAD

**Issue by Darkosto** [Malorolam/LootBags#40]
Hey Mal, 

Could you take a look at error I'm getting on world load. Something sparks a chain of NPE errors and causes the client to get stuck on world loading. It only happens on developed save files, I'm able to load a new world and then switch over to the older saves just fine.

I found this:
http://pastebin.com/ePHdL9R3

within this latest log:
https://gist.github.com/Darkosto/fc7fceda8e1e9b3feff349974522b8e7

Forge: 2185
MC: 1.10.2
LootBags: 2.2.2

**Comment by Malorolam** [comment]
I'm not getting this problem in my personal pack or with only Lootbags added.  Does this happen on loading any world, or just specific ones?

**Comment by Malorolam** [comment]
I think I figured out why it's happening, the line that's NPEing is the one where I get the tile entity in the client.  For whatever reason, the packet is being received before the forge handler is loaded, causing the NPE.  Should be fixed in the next update.

**Comment by Darkosto** [comment]
Okay cool! Sorry, I was away from my desk during your response.

**Comment by GenDeathrow** [comment]
@Malorolam  I think since 1.8.9 you have to make it thread safe by adding it the the task scheduler. http://www.minecraftforge.net/forum/index.php?topic=20135.0

**Comment by Malorolam** [comment]
It should be fixed more properly now.
