### ISSUE TITLE
Config file?

### ISSUE THREAD

**Issue by deividaslord** [Malorolam/LootBags#41]
Hello, i downloaded and installed your lootbag mod in to my modpack. But i cant seem to find the config file with all items possible drops. Because now it drops magicalculture´ rare seeds in common bags. -_- So i would like to ask if its possible to change the drops and drops-rates from the bags? I couldn't seem to find the config file or any commands in-game.

**Comment by Malorolam** [comment]
By default, the bags generate a general loot set from the primary vanilla loot sources, this isn't inherently written anywhere.  To change an item's drop chance you need to whitelist the item to overwrite the default data.  You can check the loot tables with the lootbags_itemdump command, this will make a text file in the dumps folder that you can use to find the items you want to tweak.  The file will be full of lines that look like this: minecraft:iron_chestplate:0:1.340:5  
The first two words identify the modID and item name, they need to be kept the same as in the dump file.  The first number is the metadata of the item, that also should stay the same.  The second number is the adjusted drop chance of the item in percent, this varies depending on how many items there are in the table.  The last number is the weight of the item, this is what you'll want to decrease to make something rarer when whitelisting it.
To convert this line to the line needed for the whitelist, replace the the second number, 1.340 in that line above, with two numbers separated by a colon.  The first number is the minimum number of items that you'll get, the second is the maximum number of items.  So converting the line above to work would end up looking like: minecraft:iron_chestplate:0:1:1:5

**Comment by deividaslord** [comment]
I have deleted some of the seeds from the list in the LootBagsItemDump file but they do still appear in the bags (once the game was closed), why ? bug?
Im talking about agriculture seeds. 

Here on the picture you see it can drop ghast, diamond, emerald seeds (the highlighted once)
![capture](https://cloud.githubusercontent.com/assets/24681210/21408669/8f471fc4-c7d6-11e6-8f2b-5a70abca4525.PNG)

Here is my dump file, you can see it is not on the list.
[LootBagsItemDump.txt](https://github.com/Malorolam/LootBags/files/667505/LootBagsItemDump.txt)

**Comment by Malorolam** [comment]
The dump file is just a list of what's in the tables when you run the command to make manipulating the tables easier, it doesn't actually control what the mod can give you.  To remove an item you have to blacklist it in the lootbags.cfg config file and to change the weight or drop amounts you need to whitelist it like I indicated in my last post.

**Comment by deividaslord** [comment]
Okay, im very sorry and im so good at this. So i would ask you again, because i cant neither find it on internet. So what did i type wrong or is it in the wrong place? 

![capture](https://cloud.githubusercontent.com/assets/24681210/21410960/1a735e56-c7e5-11e6-9f81-277328524219.PNG)
It could be very nice of you if you could write an example for me. Sorry again.

**Comment by Malorolam** [comment]
The blacklist entries are right, just in the wrong place.  That blacklists items from being recycled in the Loot Recycler, the general blacklist is in a different area under "blacklisted items", it should be near the start of the config file.
