### ISSUE TITLE
No lootbags on server

### ISSUE THREAD

**Issue by Rithenar** [Malorolam/LootBags#42]
Hi Maloralam

We have your mod in a Curse pack we put together and it was working fine in SSP but when we use it in our server we get no lootbags at all. We are using 1.10.2 in Rith's Pack on Curse.  Checked configs and I see no conflicts so not sure what is going on...

**Comment by Malorolam** [comment]
It's not a Lootbags issue, I tested a server with just Lootbags and got bags just fine.  There's nothing wrong with the configs either, at least the version Curse gave me.

**Comment by Rithenar** [comment]
Hmm...ok let me do some more testing and see if I find what is up. Thanks Maloralam.
