### ISSUE TITLE
No Loot Table

### ISSUE THREAD

**Issue by Waterghosteus97** [Malorolam/LootBags#48]
When i downloaded the mod Loot bags weren't dropping, so I went into creative and looked at the loot bags. When I did it said there was no loot table, I went into the config and couldn't really understand anything in there. I am playing on a mac in minecraft version 1.10.2

**Comment by Malorolam** [comment]
Delete both configs and let them get remade by the game.  If it's still happening, I'll need both config files and the runtime log, so put them in pastebin and link them.

**Comment by MrRiptide** [comment]
That seems to work for me, I don't know about the other person, though...

**Comment by Waterghosteus97** [comment]
Thank you, that fixed my problem. You are an amazing mod creator.
