### ISSUE TITLE
[Issue] Loot-Bag crash "n must be positv"

### ISSUE THREAD

**Issue by accessdenied0** [Malorolam/LootBags#5]
Hi dear @Malorolam,

First up I played with your mod a long time now and because of this I'm pretty sure this issue isn't directly your mods fault... but I'm sure you help with/fix this issue this for further use...

I tried to open a "Legendary Loot Bag" and get this http://pastebin.com/tm2N4QNq crash-report,

I hope you can help,

access_denied

**Comment by Malorolam** [comment]
From what it looks like there is an item in your loot table which has a minimum stack size greater than it's maximum stack size, causing the <0 exception.  I can certainly fix the issue in the next version, but I don't have an ETA for when I'll finish it.  In the meantime, make sure that any whitelisted items have max stack sizes greater than 0 and see if that's the source of the issue.

**Comment by accessdenied0** [comment]
Hey @Malorolam,

I was aware of that, thank you anyway for fixin' this bug.
But I got a question for white-listing: I never black-listed or white-listed anything and because of this I use the standard loot tables. Is there a possible way to print these in a file out? This would be helpful to track the broken item down.

access_denied
