### ISSUE TITLE
Localised name for Custom Lootbags

### ISSUE THREAD

**Issue by CriticalMole** [Malorolam/LootBags#54]
In the config word document it says the language file needs to be updated, does this mean the one inside the jar, or is there a way to do this without recompiling everything (pretty new at that sort of thing)

**Comment by Malorolam** [comment]
You can do this through a resource pack.
http://www.minecraftforum.net/forums/mapping-and-modding/resource-packs/resource-pack-discussion/1256295-how-to-make-a-language-changing-names-of-items?comment=4

**Comment by CriticalMole** [comment]
Ok, thanks :)
