### ISSUE TITLE
Boss Dropping Custom Bags

### ISSUE THREAD

**Issue by CriticalMole** [Malorolam/LootBags#56]
I have a range of lootbags I want to drop from Boss mobs and rare player as PvP kill drops but otherwise be compeltely secret and not drop any other way below is an example version of one of the bags I created.
There are about 10 of these bags, I want one to drop every time from the wither and the ender dragon, but only one at random
Can you tell me what I am doing wrong as the Withers are not dropping them

$STARTBAG:lootbagExample:30
    $BAGCOLOR:255|153|0:53|98|191
    $ISSECRET:true
    $BAGTEXTCOLOR:$BLUE
    $BAGTEXTUNOPENED:$BLUE:Example
    $BAGTEXTOPENED:$BLUE:Example
    $BAGTEXTSHIFT:Example
    $BAGTEXTSHIFT:Example
    $BAGTEXTSHIFT:$BLUE:Example
    $CRAFTEDFROM:$NULL:0
    $PASSIVESPAWNWEIGHT:0
    $PLAYERSPAWNWEIGHT:10
    $MOBSPAWNWEIGHT:0
    $BOSSSPAWNWEIGHT:100
    $USEGENERALLOOTSOURCES:false
    $MAXIMUMITEMS:4
    $MINIMUMITEMS:4
    $PREVENTITEMREPEATS:fixed
    $EXCLUDEENTITIES:true
    $BLACKLISTRECYCLER:true
    $STARTENTITYLIST
        $VISIBLENAME:Example
    $ENDENTITYLIST
    $STARTWHITELIST
        minecraft:flint_and_steel:0:1:64:20
        minecraft:flint_and_steel:0:1:64:20
        minecraft:flint_and_steel:0:1:64:20
        minecraft:flint_and_steel:0:1:64:20
    $ENDWHITELIST
$ENDBAG:lootbagExample

[Edited just to add this... the actual bags have unique loot in, just trying to avoid ingenious people figuring out what I am up to :P ]

**Comment by Malorolam** [comment]
If the drop resolution in lootbags.cfg is default, that bag has a 10% chance to drop from bosses and a 1% chance to drop from players.  Additionally, how you have the entity list set up only something that has the visible (so player or name tag given) name of Example can drop the bag.  If you change it to
`$STARTENTITYLIST
    $INTERNALNAME:WitherBoss
    $INTERNALNAME:ENDERDRAGON
    $INTERNALNAME:Player
$ENDENTITYLIST`
it will drop only from those three.  The last name entry won't work until I finish the patch I'm working on right now though.
Alternatively, if you don't have any other mods that add bosses or don't mind this happening for all bosses, you can just nix the entity list.
As for the guaranteed drop and only one, making all the boss bags drop weight to match your resolution and keeping B:"Limit bag drop to one bag per death"=true should give you the behavior you want.

**Comment by CriticalMole** [comment]
Thanks, that pointed me right at the solution I needed!
