### ISSUE TITLE
When do lootbags access the loot tables?

### ISSUE THREAD

**Issue by CriticalMole** [Malorolam/LootBags#57]
Me Again!
I am wondering when the loot bags tap into the loot tables to generate their loot.  We have added a load of drops to the various tables through Minetweaker and according to some testing (100's of bags) these are not being drawn into the bags themselves.

Any insight you could give would be greatly appreciated.

Mole.

**Comment by Malorolam** [comment]
I do my general table pulling in postInit, which is the latest I'm willing to do any loading tasks.  Last I looked, Minetweaker does it's thing on server load.

This is something that's been a bit of an issue in the past and most ideas I've had to solve it cause other issues that affect everyone to fix a minority case.
