### ISSUE TITLE
Question about whitelisting

### ISSUE THREAD

**Issue by Himoteph** [Malorolam/LootBags#58]
Greetings, I have a question about whitelisting the lootbag drops...Is it at all possible to setup a blanket whitelist of all craftable items in a specific mod? For example: Botania or Kingdom Keys. If so...how?

**Comment by Malorolam** [comment]
No, blanket whitelisting would cause a large number of issues that would be significantly more trouble than that feature is worth.  While limiting things to only items that have crafting recipes, that still introduces the issue of compatibility with recipe tweaker mods and NBT data added as part of the crafting code.
