### ISSUE TITLE
Question about wording on config setting

### ISSUE THREAD

**Issue by CriticalMole** [Malorolam/LootBags#59]
This is the resolution of the bag drop chances.  Only change this if you want bags with rarity resolutions > 0.1%

set to 1000 by default, am I right in thinking that the > should be a < and that this is the number used in determinning rairty i.e. X in [Set Value] chance of dropping?

**Comment by Malorolam** [comment]
As you increase that value, it increases the random number rolled to be compared to the bag weight, which allows you to have a larger range of bag weights, since a bag's drop chance is expressed as its weight/the resolution.

**Comment by CriticalMole** [comment]
Thanks
