### ISSUE TITLE
Custom Loot Tables

### ISSUE THREAD

**Issue by rainbowdude6** [Malorolam/LootBags#63]
i was attempting to add a custom loot table to the lootbags but this happened 

![2017-04-09_15 46 53](https://cloud.githubusercontent.com/assets/24943310/24840492/07e7c4be-1d3c-11e7-8ae8-ca8625069b19.png)
![2017-04-09_15 46 55](https://cloud.githubusercontent.com/assets/24943310/24840489/07e5878a-1d3c-11e7-96bb-aa82201b7d05.png)
![2017-04-09_15 46 57](https://cloud.githubusercontent.com/assets/24943310/24840490/07e60660-1d3c-11e7-89f2-23f03728eb67.png)
![2017-04-09_15 46 58](https://cloud.githubusercontent.com/assets/24943310/24840491/07e6bfc4-1d3c-11e7-9430-e97a9a26db26.png)
![2017-04-09_15 46 59](https://cloud.githubusercontent.com/assets/24943310/24840493/07e99d84-1d3c-11e7-98ca-81d57ad68bdb.png)

here is my config file

[Lootbags_BagConfig.txt](https://github.com/Malorolam/LootBags/files/908493/Lootbags_BagConfig.txt)
[lootbags.txt](https://github.com/Malorolam/LootBags/files/908492/lootbags.txt)

here is my loot table file

[1.txt](https://github.com/Malorolam/LootBags/files/908496/1.txt)

thanks 

     -Rainbow

**Comment by Malorolam** [comment]
It's because there are no items in any of the bags.  You have no whitelisted items and a non-existent ChestGenHook.
Check your spelling on line 65 of lootbags.cfg to make sure it is correct.  Also if that is intended to be something added by a tweaker mod for dungeon loot, most of those run their code after I pull the tables.

**Comment by rainbowdude6** [comment]
![capture](https://cloud.githubusercontent.com/assets/24943310/24840656/ce8ae874-1d3e-11e7-8e82-537024196862.PNG)
there is a photo of where the loottable is located can you tell me if i made a mistake

thanks
     -Rainbow

**Comment by Malorolam** [comment]
That won't work at all, the save-based loot tables load when the server starts, which is after I pull the tables.  Besides, as I rip the items directly out of the pool structure that the jsons are designed around, using the whitelist functionality of my mod is more efficient.

**Comment by rainbowdude6** [comment]
ok thanks alot

     -Rainow

**Comment by rainbowdude6** [comment]
is it posible to have it not use the loot tables and just use the white listed items?

     -Rainbow

**Comment by Malorolam** [comment]
Yes.

**Comment by rainbowdude6** [comment]
how would i do so

**Comment by Malorolam** [comment]
[https://github.com/Malorolam/LootBags/wiki/Tutorials](The tutorial page) has tutorials for whitelisting items.

**Comment by AutisticMC** [comment]
Very Good Info
