### ISSUE TITLE
unkown error

### ISSUE THREAD

**Issue by DeathSaintfool** [Malorolam/LootBags#67]
when i try todo /lootbags_dumphelditem , it says unknown error.
any way to solve this?

**Comment by DeathSaintfool** [comment]
this is what the console says 
https://pastebin.com/TmL9dmwj

**Comment by Malorolam** [comment]
It means that the command doesn't exist, which means your Lootbags version is before 2.3.5.

**Comment by MeisterGeekz** [comment]
Hi, I'm part of the group with DeathSaintfool, we're running Version 2.3.7 on the server. If we have nothing in our hands while executing the command it says 
Lootbags Held Item Dump Failed: Player has no held item. 

But if we  have something in our hands it gives the error:
An unknown error occurred while attempting to perform this command

And the paste above shows what appears in the console

**Comment by Malorolam** [comment]
It'll be fixed in 2.3.8.
