### ISSUE TITLE
render bug

### ISSUE THREAD

**Issue by DeathSaintfool** [Malorolam/LootBags#68]
my custom lootbag is a pink block it works and all .
only a render issue
![2017-05-02_17 57 19](https://cloud.githubusercontent.com/assets/27924871/25626816/0243c5f8-2f61-11e7-9ddd-61c2363a3238.png)
this is the code we used https://pastebin.com/qwKD7Gp4

**Comment by Malorolam** [comment]
Follow Tutorial 6 on the [tutorials page](https://github.com/Malorolam/LootBags/wiki/Tutorials).

**Comment by MeisterGeekz** [comment]
I've followed the steps you listed and added the localisation to resource pack. But I'm still getting the same issue. The name is working fine but none of the other text like the $BAGTEXTOPENED is showing and the bags are still showing the pink block. The loot inside is as should be.

I'm not wanting to use a custom texture

https://pastebin.com/C5dSGf3b

Paste of the new bag added inside Lootbags_BagConfig.cfg

**Comment by Malorolam** [comment]
I checked the bag and it's working perfectly fine on my end.  Perhaps try a fresh download of the mod, possibly the generic texture or json got corrupted somehow.  

The tooltip text probably is some interaction with the mod you're using for advanced info, I've never encountered that issue before with the normal contenders.

Also how you have it set up, the bag cannot drop from something named Player (as in the mod developer), just making sure you know the behavior that's going to occur.

**Comment by MeisterGeekz** [comment]
Ok I'll give it a try thank you very much.

The player thing was copied from another file, I actually meant to remove that. Glad you pointed it out, I would have totally forgot otherwise
