### ISSUE TITLE
Crafting bag upgrades.

### ISSUE THREAD

**Issue by Dominance** [Malorolam/LootBags#7]
So it would seem that you can remove all but one item from a loot bag, And still use it for crafting the next tier items. Not sure if this was meant to be like this or not.

**Comment by Malorolam** [comment]
Yes, that's intended.

**Comment by Dominance** [comment]
ok so I guess limiting the amount of items per bag to 1 is the only way to basically make this less op?

**Comment by Malorolam** [comment]
Pretty much, alternatively you can increase the number of bags needed to upgrade up as compensation.

**Comment by Malorolam** [comment]
Resolved with the "Prevent Merging Opened Bags" config option.
