### ISSUE TITLE
Custom textures, how.

### ISSUE THREAD

**Issue by 5rJoud** [Malorolam/LootBags#70]
> If you are using a custom texture, you will need to add the new texture and model. Create the texture for your custom bag in the image editing software of choice. Save the image as ItemTexture.png. Place this image in the textures\items folder made above. In the models\item folder, create a file named .json. Within the file, copy the following into it:
`{`
`"parent": "item/generated",`
`"textures": {`
`"layer0": "lootbags:items/<bag unlocalized name>ItemTexture"`
`}`
`}`
Repeat this step for each new bag, creating a new texture and model .json file for each bag.

Can you please give an example. Naming a file .json is impossible, I'm assuming you mean bagname.json . But what is even more confusing is that there is no punctuation between the item name and its texture name in the json code. Is it a slash or a period? I tried both and no luck and I even tried the name and the texture in one word like your tutorial suggests.

**Comment by Malorolam** [comment]
The lacking file name is fixed now.

For example, the common loot bag has the unlocalized name of lootbagCommon, so its model .json file is named lootbagCommon.json and it's contents look like this:
`{`
`    "parent": "item/generated",`
`    "textures": {`
`        "layer0": "lootbags:items/lootbagCommonItemTexture"`
`    }`
`}`

Hopefully that helps.
