### ISSUE TITLE
What is wrong here heed som help

### ISSUE THREAD

**Issue by PSILONCRAFT** [Malorolam/LootBags#71]
Server crashes and gives this error log file

[crash-2017-05-26_00.42.24-server.txt](https://github.com/Malorolam/LootBags/files/1030401/crash-2017-05-26_00.42.24-server.txt)

**Comment by Malorolam** [comment]
From what it looks like is you have some issue with the config files.  Post them both here so I can point out the issue and add error handling for it.  If you haven't done any changes to them, it's probably due to a config initialization error, delete both of them and let them build again.

**Comment by PSILONCRAFT** [comment]
here they are

[lootbags.zip](https://github.com/Malorolam/LootBags/files/1033401/lootbags.zip)

**Comment by Malorolam** [comment]
It looks like you're using duplicate IDs in a couple places, 24 is one that I saw, there may be more.  The next version will have better error handling for config issues.

**Comment by PSILONCRAFT** [comment]
Yeah i Did see that. 

A nother issue is that the lootbagnames doenst show as supposed ingame.
Is there a max lenght for lootbagnames

**Comment by PSILONCRAFT** [comment]
Ok
