### ISSUE TITLE
Client crash on load/startup

### ISSUE THREAD

**Issue by sharkck** [Malorolam/LootBags#73]
Launcher is reporting the game crashed due to Lootbags.  Just updated to 2.3.9 from 2.3.8.
"The game crashed whilst there was a severe problem during mod loading that has caused the game to fail
Error: net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from Loot Bags (lootbags)"

Here is a copy of the crash log:
[crash-2017-06-09_18.23.55-client.txt](https://github.com/Malorolam/LootBags/files/1065369/crash-2017-06-09_18.23.55-client.txt)
 
"Lootbags !!CONFIG ERROR!!    Bag crafting command at line 8 has error: Too few words, it needs the command, the source bag name, and the number of bags needed."

**Comment by Malorolam** [comment]
Read the error, find the problem, and fix it.
If you're not edited the bag config at all, this means it didn't generate correctly.  Delete the lootbags configs and let them regen.

**Comment by sharkck** [comment]
That fixed the problem.  I'm assuming that there's something 2.3.8 has that 2.3.9 doesn't like?
I'll attach the configs in case it helps find a fix for it. I'm sure I'm not the only one.
[Lootbags_BagConfig.txt](https://github.com/Malorolam/LootBags/files/1065432/Lootbags_BagConfig.txt)
[lootbags.txt](https://github.com/Malorolam/LootBags/files/1065433/lootbags.txt)

**Comment by Malorolam** [comment]
The problem was always there, 2.3.9 added in more aggressive error handling for the bag config.  The configs not generating correctly is an issue I'm not sure how to fix, for all I know the problem is present in how Forge handles large numbers of configs generating for the first time, but how my bag config works makes it more apparent for me.
