### ISSUE TITLE
[1.11.2] Item bug

### ISSUE THREAD

**Issue by nicuch** [Malorolam/LootBags#79]
Items name should be lower-case.

**Comment by Malorolam** [comment]
This is a very good example of how not to post an issue report, providing no useful data on the actual problem so that the author can fix it, instead making a vague statement.

**Comment by nicuch** [comment]
Okay, so I put the mod, started forge and items are not okay. Texture is missing and items name are the item string id. You should change item string id with lower-case char because on 1.11.2 the id is case-sensitive. Sorry for the vague statememt. Also I don't speak english.

**Comment by Malorolam** [comment]
Did you move any files from any older version?  When the standards changed I had to change all of the default bag names, so if you're using older configs they're going to be the wrong names.

**Comment by nicuch** [comment]
*facepalm* Thanks, I removed old config file and it worked.
