### ISSUE TITLE
Crash on opening certain bags: java.lang.NullPointerException: Rendering screen

### ISSUE THREAD

**Issue by NicholasThong** [Malorolam/LootBags#82]
Full Log: https://paste.ee/p/PsbIS

Almost certain crash each time a player opens a lootbag.

-- Head --
Thread: Client thread
Stacktrace:
	at net.minecraft.client.gui.inventory.GuiContainer.func_146977_a(GuiContainer.java:242)
	at net.minecraft.client.gui.inventory.GuiContainer.func_73863_a(GuiContainer.java:99)
	at net.minecraftforge.client.ForgeHooksClient.drawScreen(ForgeHooksClient.java:382)
	at sun.reflect.GeneratedMethodAccessor36.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at Reflector.callVoid(Reflector.java:547)

-- Screen render details --
Details:
	Screen name: mal.lootbags.gui.LootbagGui
	Mouse location: Scaled: (320, 176). Absolute: (960, 529)
	Screen size: Scaled: (640, 353). Absolute: (1920, 1058). Scale factor of 3

**Comment by Malorolam** [comment]
This crash does not reflect opening the gui, the code that is crashing is related to a null itemstack being right-clicked in a slot.  Which means something, somewhere, is putting a null itemstack in a slot and 1.11 minecraft freaks out and crashes if it encounters a null reference instead of handling it.
I can't duplicate the issue on my test setup, update Forge to 13.20.1.2429 and remove Optifine and see if it still happens.

**Comment by NicholasThong** [comment]
Updated Forge to 13.20.1.2429 and removed Optifine. Tested with a couple of dozen of lootbags and no issue. Re-enabled Optifine and it was all good. Seems to be an issue with the recommended version of 1.11.2 Forge. Updating to 13.12.1.2429 fixed the issue. Thanks for your help! I'll re-update this thread of another issue regarding this crops up.

**Comment by NicholasThong** [comment]
So a player had another crash today.
Log: https://paste.ee/p/v4ErM

It seems almost identical to the one I had originally.

**Comment by Malorolam** [comment]
I'll put together a fix that should fix the issue from anything on my end, I don't know if it'll fix the problem as it might be coming from some other mod being naughty in the inventory in general instead of directly related to one of my slots.

**Comment by spaz926** [comment]
Same issue on Forge 13.20.1.2393.

https://paste.ee/p/5LUSQ

@NicholasThong updating to 13.20.1.2429 fixes the issue?

**Comment by Malorolam** [comment]
You're having the same issue because you didn't update to 2.4.3 nor use the latest recommended version of Forge.

**Comment by NicholasThong** [comment]
Haven't run into the issue lately, will reopen if it re-occurs. @spaz926
