### ISSUE TITLE
Ask for Repost Permission

### ISSUE THREAD

**Issue by P1nWheel0v0** [Malorolam/LootBags#84]
Hi, my name is PinWheel, I really like your mod. Those loot bags are very useful and easily get the items. I wonder if I can repost this mod on MCBBS which is the largest Chinese minecraft forum. Due to the barrier of language, most Chinese players are not able to play or even find this great mod. Thus I would like to introduce this mod to more Chinese players so that they can enjoy your mod as well. I will also help with the zh_CN.lang file update on your Github.
The entire repost will obey the rules list below and your own special requests.

- I will NOT take any credits of the mod and I will clearly state your official website (Curseforge and Github) at the head of my repost page.

- I will give the official download link directly and clearly note that "This is the official download link, please click here first"

- (Optional) In a case of the network firewalls (government policy stuff...) and net work speed, I probably prepare another mirror link for backup. The mirror will direct to an Ad-free page (very like Dropbox).

- Last but not the least, I will not use this mod to get profit/benefit in terms of money, etc... And I will clearly state that anyone who uses this mod must not use it to make money.

I will be really appreciated if you can give me the permission.
Anyway, thank you for bringing us such an amazing mod and so much fun.

Yours sincerely,
PinWheel

**Comment by Malorolam** [comment]
Is there a reason why Curse isn't the primary method of finding mods?  Just connectivity/policy issues or community habit?  
I have no issue with people making posts on forums pointing out my mod, as long as it's clear that I'm the creator and everything links directly to the Curse and Github pages.  Mirror links I'm not as much of a fan of, there inevitably is some desync with updates, which can cause issue reports on things I've already fixed.  As long as you make clear that that for the most up-to-date version the Curse page should be used, it'd be fine in this case.  This is basically everything you said above, so go ahead.  
I would greatly appreciate an updated zh_CN.lang file, the one I have is very outdated, it was last updated at the end of 1.7.10 I think.  I won't make a whole version just for one .lang file, but the updated one will be added in the version after I get it.
