### ISSUE TITLE
Quick Question

### ISSUE THREAD

**Issue by Boolyman** [Malorolam/LootBags#85]
Will the config file syntax for your 1.12 Lootbags version be the same as 1.10?  I am kinda twiddling my thumbs waiting on your update, so I want to at least start working on my bag contents list now.

**Comment by Malorolam** [comment]
As far as I'm planning, nothing is changing significantly.  However, I am having slight difficulty in convincing the new json recipe system to let me do the dynamic recipes that are in place now; while there's a handler that functions like the old system, I don't know if it's something that will persist through other updates or is just going to get deprecated.
