### ISSUE TITLE
Alpha Build?

### ISSUE THREAD

**Issue by Boolyman** [Malorolam/LootBags#87]
Is there a place we can download the alpha build for 1.12.1?

**Comment by Malorolam** [comment]
No, I as a general rule don't make alpha/beta builds, I'm not going to leave parts of the mod unfinished intentionally and how Lootbags works, there are very few features that could be shipped in an unfinished state and still have a functional mod.

**Comment by Boolyman** [comment]
Just checking in on the progress of a 1.12+ release.
