### ISSUE TITLE
1.12.1 support?

### ISSUE THREAD

**Issue by KristjanKr** [Malorolam/LootBags#88]
Hey is this mod still being worked on, haven't seen update on it since 10th of august. And was wondering if this mod will get updated to 1.12+ or not.

**Comment by Malorolam** [comment]
Yes, the mod is still getting support, 1.12.1 is coming eventually.

**Comment by Iteries** [comment]
Asking or more so nudging on any updates..  really like this mod as we can add in mods loot or special drops.  This is my last mod not up to date.  Do say keep up the good work.

**Comment by Boolyman** [comment]
Soon^tm

**Comment by MadRatSRP** [comment]
Dont forget about update please.
