### ISSUE TITLE
How to add cobblestone to Loot Bag recycler?

### ISSUE THREAD

**Issue by Tyranuss** [Malorolam/LootBags#92]
As the title says, how to do that? I'm feeling kinda cheaty and want to have fun with this mod, but I don't know how to accomplish this. Please help. :(

**Comment by Malorolam** [comment]
Under the recycler section of lootbags.cfg, there's a section called recycler whitelist.  You can whitelist an item like you would in a bag there and it will be recyclable.  
So cobble would be added like: minecraft:cobblestone:0:<weight>
The weight is inverse of the loot stuff value, so if you want it not worth much, give it a higher weight.

**Comment by Tyranuss** [comment]
Err doesn't work mate. I'm stupid. Is the position of these signs important <>?

**Comment by Malorolam** [comment]
Oh no, the `<weight>` is a replacer for number, so it'd be something like minecraft:cobblestone:0:25

**Comment by Tyranuss** [comment]
Cool :D It's working now. Thanks mate! :*
