### ISSUE TITLE
Console Spam

### ISSUE THREAD

**Issue by tyler489** [Malorolam/LootBags#94]
I use spawners with custom nbt tags on my server. they currently spawn Sponge.Human with custom names and drops however everytime one spawns this appears in console ```class: EntityHuman['Steak!'/352, l='world', x=391.53, y=111.00, z=366.89]; This is probably an error somewhere so going to assume this is a monster.
05.11 09:24:18 [Server] INFO [09:24:18] [Server thread/INFO] [FML]: [LOOTBAGS]: Found entity of class: EntityHuman['Steak!'/352, l='world', x=391.53, y=111.00, z=366.89]; This is probably an error somewhere so going to assume this is a monster.
05.11 09:24:18 [Server] INFO [09:24:18] [Server thread/INFO] [FML]: [LOOTBAGS]: Found entity of class: EntityHuman['Steak!'/352, l='world', x=391.53, y=111.00, z=366.89]; This is probably an error somewhere so going to assume this is a monster.
05.11 09:24:18 [Server] INFO [09:24:18] [Server thread/INFO] [FML]: [LOOTBAGS]: Found entity of class: EntityHuman['Steak!'/352, l='world', x=391.53, y=111.00, z=366.89]; This is probably an error somewhere so going to assume this is a monster.
05.11 09:24:18 [Server] INFO [09:24:18] [Server thread/INFO] [FML]: [LOOTBAGS]: Found entity of class: EntityHuman['Steak!'/352, l='world', x=391.53, y=111.00, z=366.89]; This is probably an error somewhere so going to assume this is a monster.``` is there a way to remove this or blacklist them from droping lootbags

**Comment by Malorolam** [comment]
In lootbags.cfg, set 
`    # Setting this to false will disable many of the info messages, only showing errors in the log.`
`    B:"Verbose Mode"=true`
to false.

**Comment by tyler489** [comment]
Thanks. but is there a way to make all Sponge.Humans not drop lootbags?
