### ISSUE TITLE
Loot recycler loses items when broken

### ISSUE THREAD

**Issue by ghost** [Malorolam/LootBags#95]
The number of items “eaten” by the loot recycler is reset to zero when you break and re-place the block.

**Modpack**: The Simple Life 2
**Minecraft version**: 1.10.2
**Forge version**: 12.18.3.2511
**LootBags version**: 2.3.9

**Comment by Malorolam** [comment]
Yes, default behaviour of a block is it doesn't save the data to the item when broken.
Low priority for 1.10.2, Medium-Low for 1.12.2.

**Comment by PapiDimmi** [comment]
Why low priority? It really sucks losing your loot.

**Comment by Malorolam** [comment]
Done for 1.12.2 and 1.10.2.
