### ISSUE TITLE
1.12.2 Common Lootbag has wrong texture and doesnt open

### ISSUE THREAD

**Issue by MadRatSRP** [Malorolam/LootBags#98]

**Comment by Malorolam** [comment]
Delete Lootbags_BagConfig.cfg and run the game again.

**Comment by Andronomos** [comment]
I just installed the mod for the first time in 1.12.2 and am having this problem. I deleted the configs and restarted the game but the bags still have the wrong texture. They look like this: https://i.imgur.com/ANlbHDg.png

**Comment by Malorolam** [comment]
That looks like a texture wrapping issue.  What other mods are you using?

**Comment by Andronomos** [comment]
@Malorolam Here is a list of all the mods I currently have installed alongside LootBags in 1.12.2.

[Installed Mods (Pastebin)](https://pastebin.com/08UB5YHj)

**Comment by Malorolam** [comment]
Alright, I'll take a look to see if I can fix it.

**Comment by Malorolam** [comment]
I'm not getting it with tinyprogressions-1.12-3.2.10, their changelogs looks like they fixed it on their end.
