### ISSUE TITLE
1.12 LootBags crash on Forge 2555

### ISSUE THREAD

**Issue by DaeZak** [Malorolam/LootBags#99]
Minecraft Version: 1.12.2
Forge Build: forge-1.12.2-14.23.1.2555
LootBags Version: LootBags-1.12.2-2.5.0

The game crashes on load.  I removed all other mods except for LootBags and the issue still occurs.  Hopefully this helps let me know if there is anything I can do or further information that you need.

[crash-2017-12-04_09.40.23-client.txt](https://github.com/Malorolam/LootBags/files/1527476/crash-2017-12-04_09.40.23-client.txt)

**Comment by Malorolam** [comment]
Update to 2.5.1

**Comment by DaeZak** [comment]
Sure enough - I missed that there was a new version released.  My bad!
